### ISSUE TITLE
confused about the results of split time

### ISSUE THREAD

**Issue by biozzq** [popgenmethods/smcpp#10]
Dear Jonathan,
I have run the inference of split time for my study species using the latest SMCPP (each population include about 20-40 individuals). The generation time is about three years. From the following results, can I just infer the divergence time is 10k generations ago between CNN and CNS? If so, I think the time is somewhat too ancient. The domestication of studied animals are occurred about 10,000 years ago. And I do not know how to explain their intersection after their split(marked with red arrows).  From admixture analysis, CNN is a mixed population, I do not know whether the admixture event will affect the result. 
![image](https://cloud.githubusercontent.com/assets/15704257/23575872/39e04c4e-00d0-11e7-87a5-ecddb9613ec2.png)
![image](https://cloud.githubusercontent.com/assets/15704257/23575876/468f9724-00d0-11e7-87f3-3adbd3ecadee.png)
What is more, their effective population size results like following.
![image](https://cloud.githubusercontent.com/assets/15704257/23575877/5175a0ac-00d0-11e7-996b-60c80906e3ca.png)
I hope you can take some time to give me some suggestions. 
By the way, can I use about 20 individuals per population to infer very recent split time (about 2000-4000 years ago)?

Best
Zhuqing

**Comment by guzhongru** [comment]
Why there is a different trajectory for CNS between the last figure and first figure ?

**Comment by biozzq** [comment]
Hi @guzhongru 

I do not know why, I think they should be different because the first figure is the results of split time, the last one is just the statistic of effective population size. So I hope @terhorst can give me some suggestions about this results.

Best
Zhuqing

**Comment by mattingsdal** [comment]
I had similar issus with my organsism. I suspect you have not used the thinning option. In the smc++ paper they use --thinning 400 for all data.

**Comment by terhorst** [comment]
I have made a lot of updates to the latest version (v1.8.0) which should result in more stable estimates for small sample sizes. Could you please upgrade to this version and let me know if you still encounter problems?

**Comment by biozzq** [comment]
Dear @terhorst 

I ran the estimation of effective population size and split time with the latest `smcpp`, the results seem better than before. The domestication time for my studied population is about 10,000 years ago (about 3300 generations ago) . But I noted the effective population sizes do not have a good agreement before 3400 generations ago but not MSMC2(refer to https://github.com/popgenmethods/smcpp/issues/6). More, how can i interpret the result about the split time between CNN and CNS?
![Uploading Ne.png…]()
![Uploading Split.png…]()

Thank you
Best  
Zhuqing

**Comment by terhorst** [comment]
You might try ``--regularization-penalty 8`` (or 7) if you think the fits vary too much in the recent past. I can't promise that the outputs of MSMC2 and SMC++ are going to match up exactly since they use different models. What command are you using to run ``split``?

**Comment by biozzq** [comment]
Dear @terhorst 

Thank you. I will have a try. The commands I used for split time
`smc++ vcf2smc --mask $chr.Uncallable.bed.gz auto.chr.vcf.gz $chr.smc.gz $chr $pop1label:$pop1name $pop2label:$pop2name` to produce the joint frequency spectrum.
`smc++ split -o $out --em-iterations 20 $pop1model $pop2model 1.smc.gz 2.smc.gz 3.smc.gz 4.smc.gz 5.smc.gz 6.smc.gz ...` using the marginal estimates produced by `estimate`
Is it necessary to run `smc++ vcf2smc my.vcf.gz data/pop21.smc.gz <contig> pop2:ind2_1,ind2_2 pop1:ind1_1,ind1_2` before `split` which just change the position of population?
Best
Zhuqing

**Comment by guzhongru** [comment]
Hi Zhuqing
Can I contact with you by QQ ? Thanks.

**Comment by biozzq** [comment]
Hi @guzhongru 

It‘s OK. 370864787

**Comment by biozzq** [comment]
Dear @terhorst 

Thanks for your time #25 .  Does the following result mean the split time is about 4000 generations ago, and how can i explain their intersection ~1700 generations ago?
![admixturel](https://cloud.githubusercontent.com/assets/15704257/26283798/05130c26-3e61-11e7-8f72-9ce2373f7c78.png)

Best Wishes
Zhuqing

**Comment by terhorst** [comment]
It looks to be about 5-6 thousand generations ago. The exact split time is noted in the ``model.final.json`` file. I'm afraid I don't understand the second part of the question, about the intersection.

**Comment by biozzq** [comment]
Dear @terhorst 

Thanks.  I noted the `split` item in `model.final.json` file, but I do not know how to convert this (following) to real generation time.  It is difficult for me to understand their cross about ~1,700 generations ago, can their ongoing genetic exchange lead to this result?
```
        "split": 0.3042055762123046
    },
    "rho": 7.863957277915278e-05,
    "theta": 0.0001
```
Best Wishes
Zhuqing

**Comment by terhorst** [comment]
The split time is in coalescent scaling, so multiplying by ``2 * N0`` would yield the time in generations. Regarding the second question, I think you may have the wrong impression of what these curves represent. They are estimates of the effective population size (``Ne``) going back in time. That they would cross at a single point in time merely indicates that the effective population sizes in the two populations are estimated to be equal then. It has nothing whatsoever to do with gene flow between the two populations.
