### ISSUE TITLE
Theta error issue in split version 1.15 and 1.15.1

### ISSUE THREAD

**Issue by harlydurbin** [popgenmethods/smcpp#104]
Hi there! Since updating to v1.15 back in August, I've gotten the error below when running `split`. I updated to version 1.15.1 today to see if that would make a difference, but am still getting the same error. `vcf2smc`, `estimate`, and `plot` are all working fine, though. 
I installed SMC++ in a python virtual environment on a Linux cluster:

```
module load python/python-3.6.5
python3 -m venv ~/smcpp_venv
source ~/smcpp_venv/bin/activate
pip install cython
pip install numpy
pip install git+https://github.com/popgenmethods/smcpp
```

I also got an error about scikit-learn not being installed when I updated to v1.15.1 so I updated that as well. Command I'm using to run `split`:

```
smc++ split -o split/180301_20.raw.all_snps/eurotaurine_afrtaurine --timepoints 20 200000 estimate/180301_20.raw.all_snps/eurotaurine/model.final.json estimate/180301_20.raw.all_snps/afrtaurine/model.final.json joint_vcf2smc/180301_20.raw.all_snps.eurotaurine_afrtaurine.*
```

Error I get: 

```
/home/hjdzpd/smcpp_venv/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/home/hjdzpd/smcpp_venv/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.15.1.dev12+gf1d7b23', 'console_scripts', 'smc++')()
  File "/home/hjdzpd/smcpp_venv/lib/python3.6/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/home/hjdzpd/smcpp_venv/lib/python3.6/site-packages/smcpp/commands/split.py", line 40, in main
    args.mu = d['theta'] / (2. * d['model']['N0'])
KeyError: 'theta'
```
In these particular datasets, I've got 29 chromosomes and 10 & 11 samples per population. The debug.txt file is attached. Thanks so much for your help! Let me know if I need to clarify anything or provide more detail.

Harly Durbin
[debug.txt](https://github.com/popgenmethods/smcpp/files/2573932/debug.txt)

**Comment by grafau** [comment]
Hi Harly,

Did you manage to find a work-around? I am now hitting exact same problem with version 1.15.1.

Best,
Rafal

**Comment by grafau** [comment]
Hi @terhorst,

I noticed that "model.final.json" after cross-validation is lacking the "rho" and "theta" parameters in output of v1.15.1. In each fold's "model.final.json" these parameters are there, they are just missing in the summarized  (?) output. Probably that's why split.py complains.

Any recommendations on which theta to include in summarized "model.final.json" before it's fixed?

Cheers,
Rafal

**Comment by terhorst** [comment]
Hi, thanks for reporting and sorry for the delay. How did you generate the model.final.json files? On my test cases, split does not produce this error, so I'm wondering if they were generated with an older version?

**Comment by grafau** [comment]
Hi!

I was using v1.15.1 all along (that is for 'cv' command and 'split' command).

Below are example files from 'cv'. If I feed 'split' with any final models from independent folds, it does not throw the error. However, I am feeding splits with the final model that is at the base directory (not in fold director, which is what I assumed to be "cross-validated" model), it throws errors. Please find attached example final models from fold1
and base directory.

Base (./)
[model.final.json(.:).txt](https://github.com/popgenmethods/smcpp/files/2676803/model.final.json.txt)

Fold (./fold1/)
[model.final.json(.:fold1:).txt](https://github.com/popgenmethods/smcpp/files/2676806/model.final.json.fold1.txt)

**Comment by harlydurbin** [comment]
Hi @terhorst -
I ran the cv estimates with version 1.15 and updated to 1.15.1 when I began having issues with split. I haven't gotten back to running the cv estimates with 1.15.1 yet. Attached are the .debug.txt file from one of the population estimates, the model.final.json from fold1, and the overall (?) model.final.json. Thanks!

[debug.txt](https://github.com/popgenmethods/smcpp/files/2681045/debug.txt)
[fold1.model.final.txt](https://github.com/popgenmethods/smcpp/files/2681050/fold1.model.final.txt)
[summary.model.final.txt](https://github.com/popgenmethods/smcpp/files/2681052/summary.model.final.txt)

**Comment by grafau** [comment]
Thanks for the warning! Would you mind saying in one sentence what is the mixed success? Does it mean that the cv results are not congruent with results from previous search algorithm or that cv does not manage to get any models in some cases? 

Again, many thanks for you active development of such a great tool!

**Comment by terhorst** [comment]
In some cases CV does what I want, which is to choose a reasonable smoothing parameter that nicely balances the tradeoff between bias and variance. In other cases, it selects very poorly, and the resulting fit looks bad. The more fundamental issue is that this is an unsupervised problem, basically density estimation, and it is not obvious (to me) how to correctly cross-validate in this setting.

**Comment by harlydurbin** [comment]
Thanks for the update @terhorst!
