### ISSUE TITLE
different result in two same analyses

### ISSUE THREAD

**Issue by yuntwang** [popgenmethods/smcpp#106]
Hi,
I use the v1.12.1 smc++ to estimate my population demongraph.
Although the trend is consistent, I get different results in the same analysis.
And the second analysis I remove a group.
Why.
![pine](https://user-images.githubusercontent.com/27258713/50142031-f1425a00-02e3-11e9-815c-85933781a0c7.png)
![pine2](https://user-images.githubusercontent.com/27258713/50142032-f1425a00-02e3-11e9-8395-723511f2042c.png)

**Comment by terhorst** [comment]
Please upgrade to the latest version and re-run your analysis.
