### ISSUE TITLE
No effect of -rp or --knots on rough demographic history

### ISSUE THREAD

**Issue by twooldridge** [popgenmethods/smcpp#107]
Hello,

I'm currently trying to estimate population histories for a single population consisting of 11 diploid individuals, with unphased genomes ranging from 10x-20x. I generated input files using vcf2smc, providing masks for low coverage sites in the genome where the genotyping rate was low.

When I use both the estimate and cv command to get population histories using a random autosome, I get an output plot that looks, for lack of a better word, "chunky", rather than smooth like the history plots as seen in Terhorst et al. and shown in posts by other users here. I've attached example commands and a plot below.

```
smc++ cv 5.3e-9 smc_input/BW.chr1.MZ10772_BW.smc.gz smc_input/BW.chr1.MZ10808_BW.smc.gz smc_input/BW.chr1.MZ10813_BW.smc.gz -o estimates/BW/chr1/ --cores 8 
smc++ plot -c BW.default.pdf model.final.json
```
[BW.default.pdf](https://github.com/popgenmethods/smcpp/files/2718900/BW.default.pdf)

Unfortunately, when I drop the 'knots' or 'regularization' parameters, as recommended by the paper and github documentation, I see no real effect on the plot output. It looks similarly "chunky" regardless of what parameters I use. I've also attached an example below, where I set the regularization penalty to 2.0:

Commands:
```
smc++ cv 5.3e-9 smc_input/BW.chr1.MZ10772_BW.smc.gz smc_input/BW.chr1.MZ10808_BW.smc.gz smc_input/BW.chr1.MZ10813_BW.smc.gz -rp 2 -o estimates/BW/chr1/rp2 --cores 8 
smc++ plot -c rp2.pdf model.final.json
```
[rp2.pdf](https://github.com/popgenmethods/smcpp/files/2724211/rp2.pdf)

When I drop the 'knots' parameter to 6 I see some of the steps have been flattened out, but this effect is minimal:

[knots6.pdf](https://github.com/popgenmethods/smcpp/files/2724215/knots6.pdf)

As a side note, I've toyed with the # of folds, the thinning parameter, and estimated over different timepoints, and I see the same effect. For what it's worth, the demographic history in this population and our others meshes with our priors for what these populations have experienced, so I don't think that the results are "incorrect".

Do you have any thoughts on what might be causing this phenomenon, and if there's anything obvious I might be missing?

Thanks in advance for your help!
Brock

**Comment by terhorst** [comment]
`smc++ cv` sets the regularization penalty for you. Really, it should raise an error if you pass `-rp`; I will fix that. Try using `smc++ estimate` if you want to control it manually. Regarding the smoothness, you can enable the spline fit using the `--spline` option. The default is piecewise constant, because a) people kept inquiring why the defaults did not match PSMC/MSMC, and b) for whatever reason, I find the piecewise constant model to be more stable when doing model fitting.

**Comment by twooldridge** [comment]
Got it, that makes sense. Thanks a ton for your help!

Brock
