### ISSUE TITLE
estimate error with FloatingPointError

### ISSUE THREAD

**Issue by YindyXue** [popgenmethods/smcpp#112]
Hi, I'm trying to run the SMC++, but the estimate error blocked me.

Running the first step :

smc++ vcf2smc all.filter.final.snp.vcf.gz AS/AS.NewChr1.smc.gz NewChr1 AS:AS1,AS2,AS3,AS4,AS5,AS6,AS7,AS8,AS9,AS10,AS11,AS12,AS13,AS14,AS15,AS16,AS17,AS18,AS19
900 smcpp.commands.vcf2smc WARNING Neither missing cutoff (-c) or mask (-m) has been specified. This means that stretches of the chromosome that do not have any VCF entries (for example, centromeres) will be interpreted as homozygous recessive.
901 smcpp.commands.vcf2smc INFO Population 1:
901 smcpp.commands.vcf2smc INFO Distinguished lineages: AS1:0, AS1:1
901 smcpp.commands.vcf2smc INFO Undistinguished lineages: AS2:0, AS2:1, AS3:0, AS3:1, AS4:0, AS4:1, AS5:0, AS5:1, AS6:0, AS6:1, AS7:0, AS7:1, AS8:0, AS8:1, AS9:0, AS9:1, AS10:0, AS10:1, AS11:0, AS11:1, AS12:0, AS12:1, AS13:0, AS13:1, AS14:0, AS14:1, AS15:0, AS15:1, AS16:0, AS16:1, AS17:0, AS17:1, AS18:0, AS18:1, AS19:0, AS19:1
[W::hts_idx_load2] The index file is older than the data file: all.filter.final.snp.vcf.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: all.filter.final.snp.vcf.gz.tbi
  0%|                                                                              | 0.00/16.3M [00:00<?, ?bases/s]
922 smcpp.util   INFO Wrote 1 observations

Running the second step :

smc++ estimate -o out  1.25e-10 AS/*.smc.gz
906 smcpp.analysis INFO Loading data...
2522 smcpp.analysis INFO 0.16 Gb of data
2527 smcpp.analysis INFO 1 population
Traceback (most recent call last):
  File "/data/users/zhangjingjing/anaconda2/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.10.0', 'console_scripts', 'smc++')()
  File "/data/users/zhangjingjing/anaconda2/lib/python3.6/site-packages/smcpp/frontend/console.py", line 28, in main
    cmds[args.command].main(args)
  File "/data/users/zhangjingjing/anaconda2/lib/python3.6/site-packages/smcpp/commands/estimate.py", line 66, in main
    analysis = Analysis(args.data, args)
  File "/data/users/zhangjingjing/anaconda2/lib/python3.6/site-packages/smcpp/analysis.py", line 382, in __init__
    super().__init__(files, args)
  File "/data/users/zhangjingjing/anaconda2/lib/python3.6/site-packages/smcpp/analysis.py", line 51, in __init__
    self._watterson()
  File "/data/users/zhangjingjing/anaconda2/lib/python3.6/site-packages/smcpp/analysis.py", line 144, in _watterson
    self._watterson = estimation_tools.watterson_estimator(self._contigs)
  File "/data/users/zhangjingjing/anaconda2/lib/python3.6/site-packages/smcpp/estimation_tools.py", line 214, in watterson_estimator
    return num / denom
FloatingPointError: invalid value encountered in true_divide

How can I deal with it?
Let me know if I need to clarify anything or provide more detail.Thanks so much for your help!

**Comment by terhorst** [comment]
What does `AS/AS.NewChr1.smc.gz` look like? From the logs, it appears to have only one observation.

**Comment by terhorst** [comment]
Actually, I think someone else from your group e-mailed about this. The only line in that file is:

```
2311 smcpp.analysis DEBUG Contig(pid=('AS',), data=array([[11729719,        0,        0,       36]], dtype=int32), n=array([36]), a=array([2]), fn='AS.NewChr10.smc.gz')
```

The issue is that there are no variants at all. This should generate an error rather than crashing; I'll look into that. You might want to double check your VCF.

**Comment by YindyXue** [comment]
Thank you so much. 

The following is the content of `AS/AS.NewChr1.smc.gz`:

```
# SMC++ {"version": "1.10.0", "pids": ["AS"], "undist": [[["AS2", 0], ["AS2", 1], ["AS3", 0], ["AS3", 1], ["AS4", 0
], ["AS4", 1], ["AS5", 0], ["AS5", 1], ["AS6", 0], ["AS6", 1], ["AS7", 0], ["AS7", 1], ["AS8", 0], ["AS8", 1], ["AS
9", 0], ["AS9", 1], ["AS10", 0], ["AS10", 1], ["AS11", 0], ["AS11", 1], ["AS12", 0], ["AS12", 1], ["AS13", 0], ["AS
13", 1], ["AS14", 0], ["AS14", 1], ["AS15", 0], ["AS15", 1], ["AS16", 0], ["AS16", 1], ["AS17", 0], ["AS17", 1], ["
AS18", 0], ["AS18", 1], ["AS19", 0], ["AS19", 1]]], "dist": [[["AS1", 0], ["AS1", 1]]]}
16306990 0 0 36
```

**Comment by terhorst** [comment]
According to this output, the VCF you have used to generate this file appears to contain no mutations. Could you please check that it indeed has any? Also, for best results, please upgrade to the most recent version of SMC++.
