### ISSUE TITLE
Split with samples of different ages (ancient and modern)

### ISSUE THREAD

**Issue by nathan-nakatsuka** [popgenmethods/smcpp#114]
If we have an ancient and a modern individual that we are trying to estimate a split from with smc++, how do we add in the age of the ancient sample to have the right normalization? (or if there are 2 ancients with different ages).  Could this be implemented as a new functionality?

**Comment by terhorst** [comment]
It currently cannot be done using SMC++. I recommend estimating the split time using [momi2](https://github.com/popgenmethods/momi2), which can handle ancient samples.
