### ISSUE TITLE
smc++ abort error

### ISSUE THREAD

**Issue by nathan-nakatsuka** [popgenmethods/smcpp#116]
I have run several smc++ runs where I get the following error (or similar ones), though it appears that the smc.gz file that is produced still provides a .json file that works.  What is this error from?:

20582 smcpp.commands.vcf2smc WARNING Multiple entries found at 272 positions; skipped all but the first
*** Error in `more': free(): invalid size: 0x00000000023f1120 ***
======= Backtrace: =========
/usr/lib64/libc.so.6(+0x7d023)[0x7f372f613023]
/usr/lib64/libc.so.6(fclose+0x155)[0x7f372f600ff5]
more[0x402217]
/usr/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f372f5b7b15]
more[0x40265d]
======= Memory map: ========
00400000-00409000 r-xp 00000000 fd:00 67155696                           /usr/bin/more
00608000-00609000 r--p 00008000 fd:00 67155696                           /usr/bin/more
00609000-0060a000 rw-p 00009000 fd:00 67155696                           /usr/bin/more
023ec000-0240d000 rw-p 00000000 00:00 0                                  [heap]
7f3724000000-7f3724021000 rw-p 00000000 00:00 0
7f3724021000-7f3728000000 ---p 00000000 00:00 0
7f3728e58000-7f3728e6e000 r-xp 00000000 00:25 39865125                   /n/app/gcc/6.2.0/lib64/libgcc_s.so.1
7f3728e6e000-7f372906d000 ---p 00016000 00:25 39865125                   /n/app/gcc/6.2.0/lib64/libgcc_s.so.1
7f372906d000-7f372906e000 r--p 00015000 00:25 39865125                   /n/app/gcc/6.2.0/lib64/libgcc_s.so.1
7f372906e000-7f372906f000 rw-p 00016000 00:25 39865125                   /n/app/gcc/6.2.0/lib64/libgcc_s.so.1
7f372906f000-7f372f596000 r--p 00000000 fd:00 67152140                   /usr/lib/locale/locale-archive
7f372f596000-7f372f74c000 r-xp 00000000 fd:00 100665964                  /usr/lib64/libc-2.17.so
7f372f74c000-7f372f94c000 ---p 001b6000 fd:00 100665964                  /usr/lib64/libc-2.17.so
7f372f94c000-7f372f950000 r--p 001b6000 fd:00 100665964                  /usr/lib64/libc-2.17.so
7f372f950000-7f372f952000 rw-p 001ba000 fd:00 100665964                  /usr/lib64/libc-2.17.so
7f372f952000-7f372f957000 rw-p 00000000 00:00 0
7f372f957000-7f372f97c000 r-xp 00000000 fd:00 100666358                  /usr/lib64/libtinfo.so.5.9
7f372f97c000-7f372fb7c000 ---p 00025000 fd:00 100666358                  /usr/lib64/libtinfo.so.5.9
7f372fb7c000-7f372fb80000 r--p 00025000 fd:00 100666358                  /usr/lib64/libtinfo.so.5.9
7f372fb80000-7f372fb81000 rw-p 00029000 fd:00 100666358                  /usr/lib64/libtinfo.so.5.9
7f372fb81000-7f372fba2000 r-xp 00000000 fd:00 101908246                  /usr/lib64/ld-2.17.so
7f372fd89000-7f372fd8c000 rw-p 00000000 00:00 0
7f372fd97000-7f372fd99000 rw-p 00000000 00:00 0
7f372fd99000-7f372fda0000 r--s 00000000 fd:00 100666297                  /usr/lib64/gconv/gconv-modules.cache
7f372fda0000-7f372fda2000 rw-p 00000000 00:00 0
7f372fda2000-7f372fda3000 r--p 00021000 fd:00 101908246                  /usr/lib64/ld-2.17.so
7f372fda3000-7f372fda4000 rw-p 00022000 fd:00 101908246                  /usr/lib64/ld-2.17.so
7f372fda4000-7f372fda5000 rw-p 00000000 00:00 0
7ffce0b3d000-7ffce0b63000 rw-p 00000000 00:00 0                          [stack]
7ffce0b92000-7ffce0b94000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted

**Comment by terhorst** [comment]
This stack trace does not appear implicate SMC++ at all. Are you piping the output through /usr/bin/more?
