### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by robinengler** [popgenmethods/smcpp#124]
Hi,
Just wanted to let you know that the following modules seem to be missing from the `requires.txt` and the `setup.py`: 

* tskit
* jsonschema
* svgwrite
* h5py
* scikit-learn

**Comment by smallfishcui** [comment]
Have you solved the problem? I also lack of some dependent packages installed.

**Comment by terhorst** [comment]
@robinengler Thanks for reporting. Could you elaborate on how you encountered this error? Except for sklearn, none of those packages are directly used by SMC++. They are all dependencies coming from msprime. I'm confused why the msprime dependency did not pull them in.

**Comment by robinengler** [comment]
Hi @terhorst.
I was building the package from source with `setup.py build` and then `setup.py install` in a "mock chroot" (i.e. a sandboxed environment where only things that I explicitly require are available). 

It built just fine, but when I tried to run the smc++ command, I then got the error about the missing packages I mentioned in my opening post.

However, since every package that I install in my sandboxed environment is also packaged by me, and now that you mention that the other dependencies should be pulled by msprime, it is possible that the problem comes from my side and that the root of the problem is that my package for msprime is missing those dependencies !
I'll try to check that tomorrow when I'm back at work.

In the end, if it's working for everyone else but me, then it's likely that the problem comes from me so I wouldn't worry too much about it ;-)

**Comment by robinengler** [comment]
@smallfishcui , yes I could solve the problem by installing the list of packages that is mentioned in my first post.

**Comment by smallfishcui** [comment]
thanks. I think my problem is more similar to the other post I will write it there...

**Comment by robinengler** [comment]
@terhorst, just checked again and indeed my msprime package is missing some dependencies it should pull (svgwrite).
So then the only really missing dependency would be `sklearn`. Forget about the others as the problem with them is from my side.
With that I think we can close the issue.
Cheers
