### ISSUE TITLE
smc++ estimate 

### ISSUE THREAD

**Issue by zhangleigloria** [popgenmethods/smcpp#130]
Hi,
    I'm sorry to bother you. When I ran the second step, the following error occurred. My data is not chromosomes, it's scaffold. Contig is not long enough. Can we use this software in this case or are there  other solutions?
4401 smcpp.analysis.base INFO theta: 0.000100
4401 smcpp.analysis.base INFO rho: 0.000100
4402 smcpp.data_filter INFO Loading data...
10451 smcpp.data_filter INFO 0.00 Gb of data
10453 smcpp.data_filter INFO 1 population
19632 smcpp.data_filter ERROR All contigs are <.01cM (estimated). Please double check your data.

**Comment by terhorst** [comment]
According to this output, there is no actual data in your data files. It seems as though something unexpected happened when you ran `vcf2smc`.
