### ISSUE TITLE
estimate terminating

### ISSUE THREAD

**Issue by 18616831168** [popgenmethods/smcpp#131]
Sorry to bother you, when my calculations go to chromosome 13, the process terminates. Could you help me to see where the problem is? And what should I do ?

538249942 smcpp.optimize.plugins.progress_printer INFO EM iteration 13 of 200...
538250409 smcpp.analysis.base INFO Running E-step
567807923 smcpp.analysis.base INFO E-step completed
567808432 smcpp.optimize.plugins.loglikelihood_monitor INFO New loglik: -3774720.598160 (old: -3775095.533958 [0.009932%])
567808432 smcpp.optimize.plugins.loglikelihood_monitor INFO Log-likelihood improvement < tol=0.0001; terminating

**Comment by terhorst** [comment]
Please see https://github.com/popgenmethods/smcpp#tips-for-using-smc.
