### ISSUE TITLE
Hope you provide pre-built binaries

### ISSUE THREAD

**Issue by biozzq** [popgenmethods/smcpp#14]
Dear @terhorst 

I found you have updated smcpp to version 1.80, but it is difficult for me to install from source code. Hope you can upload the latest pre-built binaries. Thanks.

Best
Zhuqing

**Comment by wk8910** [comment]
That's right! It is pretty hard to install directly from source code.

**Comment by terhorst** [comment]
The binary auto-builder should be working again.
