### ISSUE TITLE
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by JiaoBingke** [popgenmethods/smcpp#142]
Dear terhorst,
The question presented in the title was closed 2 years ago. But I encountered this issue when I installed smcpp using conda.

I used conda 4.7.11 in miniconda. The command is "conda create -n smcpp -c http://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/ -c terhorst smcpp".

The smcpp version is 1.15.3 in smc++ file in bin directory.

I am really appreciate it if you would give me some help. Thank you very much.

**Comment by terhorst** [comment]
I think that it is something to do with pysam and channel priority, see bioconda/bioconda-recipes#5188. Instead of the command in the README, can you let me know if running

```
conda create -n smcpp --override-channels --strict-channel-priority -c conda-forge -c terhorst smcpp
```
succeeds?

**Comment by JiaoBingke** [comment]
Thank you for your reply. My colleague reinstalled pysam and then smc++ was installed successfully. The errors previous appeared in log file of cv step also disappeared. The plots of every EM step appeared in log file of cv.

**Comment by terhorst** [comment]
Glad you were able to fix this, I will close the issue.
