### ISSUE TITLE
problem to install in anaconda (win10)

### ISSUE THREAD

**Issue by rgolira** [popgenmethods/smcpp#148]
I can't find smcpp on conda 4.8.3 recently installed on my windows 10. 

the command: $ conda create -n smcpp -c conda-forge -c terhorst smcpp doesn't work.

If I search "forge", "terhorst" or "smcpp", these packages are not available.

What can I do? Are there any other way to use smc++?

**Comment by terhorst** [comment]
Sorry, but we don't offer conda builds for Windows. I don't have access to a Windows machine, nor do I fully understand software compilation on Windows. You can try building the software yourself using the instructions provided in the README. I've heard that recent versions of Windows let you run the Linux kernel, which would certainly make it easier.
