### ISSUE TITLE
VCF file format question

### ISSUE THREAD

**Issue by pstokespmb** [popgenmethods/smcpp#149]
For SMC++, would it be better to have a single VCF file consisting of all samples from multiple populations or a VCF file for each population? If one population has 30 samples, and one 250 samples, I imagine the larger population would bias variant calls.

**Comment by terhorst** [comment]
No, this should not matter at all. VCF is simply a way to represent data. It does not bias the inferences. If your concern is that more sites will be segregating in a larger sample, that is true, but SMC++ will (correctly) look at only the subsample you specified when converting the VCF. 

Now if you did something like ascertain segregating sites in one population and then type them in another, then that would cause a bias -- but that is not specific to VCF.
