### ISSUE TITLE
source code install error

### ISSUE THREAD

**Issue by lilianLC** [popgenmethods/smcpp#15]
Hi,
I am trying to install SMC using the source code.  
I get this error:

LookupError: setuptools-scm was unable to detect version for '/usr/smcpp/smcpp-1.8.0'.
Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

And I can't find this necessary files in the  source code package. Could you provide it?

Thanks
Chang Li

**Comment by terhorst** [comment]
How did you download the source code?

**Comment by lilianLC** [comment]
I download the source code in https://github.com/popgenmethods/smcpp/releases.

**Comment by terhorst** [comment]
Please follow the [build instructions](https://github.com/popgenmethods/smcpp#build-instructions).

**Comment by lilianLC** [comment]
hi，terhorst，
DO I must have root authority to install SMC++?
When I follow the build instruction, I got this error:

  Running setup.py install for smcpp ... error
    Complete output from command bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-amo2crwr-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-sjzpz6wp-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.4
    creating build/lib.linux-x86_64-3.4/smcpp
    copying smcpp/model.py -> build/lib.linux-x86_64-3.4/smcpp
    copying smcpp/contig.py -> build/lib.linux-x86_64-3.4/smcpp
    copying smcpp/version.py -> build/lib.linux-x86_64-3.4/smcpp
    copying smcpp/moran_eigensystem.py -> build/lib.linux-x86_64-3.4/smcpp
    copying smcpp/util.py -> build/lib.linux-x86_64-3.4/smcpp
    copying smcpp/jcsfs.py -> build/lib.linux-x86_64-3.4/smcpp
    copying smcpp/analysis.py -> build/lib.linux-x86_64-3.4/smcpp
    copying smcpp/__init__.py -> build/lib.linux-x86_64-3.4/smcpp
    copying smcpp/plotting.py -> build/lib.linux-x86_64-3.4/smcpp
    copying smcpp/estimation_tools.py -> build/lib.linux-x86_64-3.4/smcpp
    copying smcpp/observe.py -> build/lib.linux-x86_64-3.4/smcpp
    copying smcpp/logging.py -> build/lib.linux-x86_64-3.4/smcpp
    copying smcpp/defaults.py -> build/lib.linux-x86_64-3.4/smcpp
    creating build/lib.linux-x86_64-3.4/smcpp/spline
    copying smcpp/spline/cubic.py -> build/lib.linux-x86_64-3.4/smcpp/spline
    copying smcpp/spline/akima.py -> build/lib.linux-x86_64-3.4/smcpp/spline
    copying smcpp/spline/__init__.py -> build/lib.linux-x86_64-3.4/smcpp/spline
    copying smcpp/spline/bspline.py -> build/lib.linux-x86_64-3.4/smcpp/spline
    copying smcpp/spline/common.py -> build/lib.linux-x86_64-3.4/smcpp/spline
    copying smcpp/spline/pchip.py -> build/lib.linux-x86_64-3.4/smcpp/spline
    creating build/lib.linux-x86_64-3.4/smcpp/optimize
    copying smcpp/optimize/__init__.py -> build/lib.linux-x86_64-3.4/smcpp/optimize
    copying smcpp/optimize/optimizers.py -> build/lib.linux-x86_64-3.4/smcpp/optimize
    copying smcpp/optimize/algorithms.py -> build/lib.linux-x86_64-3.4/smcpp/optimize
    copying smcpp/optimize/exceptions.py -> build/lib.linux-x86_64-3.4/smcpp/optimize
    creating build/lib.linux-x86_64-3.4/smcpp/commands
    copying smcpp/commands/split.py -> build/lib.linux-x86_64-3.4/smcpp/commands
    copying smcpp/commands/version.py -> build/lib.linux-x86_64-3.4/smcpp/commands
    copying smcpp/commands/estimate.py -> build/lib.linux-x86_64-3.4/smcpp/commands
    copying smcpp/commands/command.py -> build/lib.linux-x86_64-3.4/smcpp/commands
    copying smcpp/commands/posterior.py -> build/lib.linux-x86_64-3.4/smcpp/commands
    copying smcpp/commands/vcf2smc.py -> build/lib.linux-x86_64-3.4/smcpp/commands
    copying smcpp/commands/__init__.py -> build/lib.linux-x86_64-3.4/smcpp/commands
    copying smcpp/commands/cite.py -> build/lib.linux-x86_64-3.4/smcpp/commands
    copying smcpp/commands/plot.py -> build/lib.linux-x86_64-3.4/smcpp/commands
    creating build/lib.linux-x86_64-3.4/smcpp/frontend
    copying smcpp/frontend/gui.py -> build/lib.linux-x86_64-3.4/smcpp/frontend
    copying smcpp/frontend/__init__.py -> build/lib.linux-x86_64-3.4/smcpp/frontend
    copying smcpp/frontend/console.py -> build/lib.linux-x86_64-3.4/smcpp/frontend
    creating build/lib.linux-x86_64-3.4/smcpp/optimize/plugins
    copying smcpp/optimize/plugins/ascii_plotter.py -> build/lib.linux-x86_64-3.4/smcpp/optimize/plugins
    copying smcpp/optimize/plugins/scale_optimizer.py -> build/lib.linux-x86_64-3.4/smcpp/optimize/plugins
    copying smcpp/optimize/plugins/parameter_optimizer.py -> build/lib.linux-x86_64-3.4/smcpp/optimize/plugins
    copying smcpp/optimize/plugins/transition_debug.py -> build/lib.linux-x86_64-3.4/smcpp/optimize/plugins
    copying smcpp/optimize/plugins/hidden_state_occupancy.py -> build/lib.linux-x86_64-3.4/smcpp/optimize/plugins
    copying smcpp/optimize/plugins/xtol_monitor.py -> build/lib.linux-x86_64-3.4/smcpp/optimize/plugins
    copying smcpp/optimize/plugins/__init__.py -> build/lib.linux-x86_64-3.4/smcpp/optimize/plugins
    copying smcpp/optimize/plugins/loglikelihood_monitor.py -> build/lib.linux-x86_64-3.4/smcpp/optimize/plugins
    copying smcpp/optimize/plugins/model_printer.py -> build/lib.linux-x86_64-3.4/smcpp/optimize/plugins
    copying smcpp/optimize/plugins/debugger.py -> build/lib.linux-x86_64-3.4/smcpp/optimize/plugins
    copying smcpp/optimize/plugins/progress_printer.py -> build/lib.linux-x86_64-3.4/smcpp/optimize/plugins
    copying smcpp/optimize/plugins/optimizer_plugin.py -> build/lib.linux-x86_64-3.4/smcpp/optimize/plugins
    copying smcpp/optimize/plugins/knot_optimizer.py -> build/lib.linux-x86_64-3.4/smcpp/optimize/plugins
    copying smcpp/optimize/plugins/analysis_saver.py -> build/lib.linux-x86_64-3.4/smcpp/optimize/plugins
    running build_ext
    building 'smcpp._smcpp' extension
    creating build/temp.linux-x86_64-3.4
    creating build/temp.linux-x86_64-3.4/smcpp
    creating build/temp.linux-x86_64-3.4/src
    gcc -pthread -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/bin/soft-ware/python/Python-3.4.6/lib/python3.4/site-packages/numpy/core/include -Iinclude -Iinclude/eigen3 -I/bin/soft-ware/python/Python-3.4.6/include/python3.4m -c smcpp/_smcpp.cpp -o build/temp.linux-x86_64-3.4/smcpp/_smcpp.o -O2 -std=c++11 -Wno-deprecated-declarations -DNO_CHECK_NAN -fopenmp -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    In file included from /bin/soft-ware/python/Python-3.4.6/lib/python3.4/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:0,
                     from /bin/soft-ware/python/Python-3.4.6/lib/python3.4/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /bin/soft-ware/python/Python-3.4.6/lib/python3.4/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from smcpp/_smcpp.cpp:509:
    /bin/soft-ware/python/Python-3.4.6/lib/python3.4/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    In file included from include/common.h:12:0,
                     from smcpp/_smcpp.cpp:501:
    include/mpreal.h: In member function 'float mpfr::mpreal::toFloat(mpfr_rnd_t) const':
    include/mpreal.h:1723:115: error: 'mpfr_get_flt' was not declared in this scope
     inline float              mpreal::toFloat  (mp_rnd_t mode)  const    {    return  mpfr_get_flt(mpfr_srcptr(), mode);    }
                                                                                                                       ^
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/bin/soft-ware/python/Python-3.4.6/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-amo2crwr-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-sjzpz6wp-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-amo2crwr-build/

And when I used the source code,I got this:
Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

Thanks
Chang Li

**Comment by terhorst** [comment]
No you do not need root. You are getting errors because:

  - Your version of mpfr is too old. (#2)
  - You downloaded the source code rather than using ``pip install git+https...``.

All of this is mentioned in the [build instructions](https://github.com/popgenmethods/smcpp#build-instructions). If you do not have experience building software on Unix, I highly recommend using the [pre-compiled installers](https://github.com/popgenmethods/smcpp/releases/latest) instead.
