### ISSUE TITLE
 WARNING Multiple entries using vcf2smc 

### ISSUE THREAD

**Issue by Anahit19** [popgenmethods/smcpp#150]
Hi,

I am running vcf2smc for one population with five individuals for each chromosomes using --mask option.

smc++ vcf2smc -d SAS03 SAS03 ../chr20_SAS.vcf.gz -m /mmg/anahit/SMC++/ref_masks/hs37d5_chr20.mask.bed.gz out/chr20_SAS03_snova.smc.gz 20 SAS:SAS01,SAS02,SAS03,SAS05,SAS06

and I noticed that it seems not the entire data have been processed. I have my output files, but I also have a warning message as follows:

17154 smcpp.commands.vcf2smc INFO Population 1:
17154 smcpp.commands.vcf2smc INFO Distinguished lineages: SAS03:0, SAS03:1
17154 smcpp.commands.vcf2smc INFO Undistinguished lineages: SAS01:0, SAS01:1, SAS02:0, SAS02:1, SAS05:0, SAS05:1, SAS06:0, SAS06:1
 20%|███████████████                                                           | 12.9M/63.0M [10:39<41:33, 20.1kbases/s]
657304 smcpp.util   INFO Wrote 260684 observations
657304 smcpp.commands.vcf2smc WARNING Multiple entries found at 88295 positions; skipped all but the first

Could you please help me with this issue.

Thank you!

**Comment by terhorst** [comment]
Hello, this warning is issued whenever VCF2SMC encounters multiple entries in a VCF at the same position. SMC++ assumes an infinite sites model, so it does not know what to do with these. It will arbitrarily select from the first such line and ignore all the rest. Frequently this can occur when your VCF contains entries for both SNPs and indels/SVs. My recommendation would be to filter your VCF so that it contains only SNPs, and at most one SNP per position.

**Comment by Anahit19** [comment]
Many thanks for you help!

**Comment by Anahit19** [comment]
Hi,

I used this command to filter multiallelic positions:

vcftools --gzvcf chr${chrom}_Sas.vcf.gz --max-alleles 2 --recode --recode-INFO-all --out chr${chrom}_Sas_nomultiallelic

Then I run it again, but still have the same issue with my data (though this time there is no warning)

1439 smcpp.commands.vcf2smc INFO Population 1:
1440 smcpp.commands.vcf2smc INFO Distinguished lineages: SAS:0, SAS:1
1440 smcpp.commands.vcf2smc INFO Undistinguished lineages: SAS:0, SAS:1, SAS:0, SAS:1, SAS:0, SAS:1, SAS:0, SAS:1
 16%|█▌        | 31.4M/198M [1:05:49<5:48:59, 7.96Kbases/s]
3956516 smcpp.util   INFO Wrote 827792 observations

I tried both smcpp/1.9.3 and smcpp/1.15.3 versions.

Thank  you again.

Anahit

**Comment by terhorst** [comment]
Sorry, but what is the issue? I no longer see any warnings or errors in this log file.

**Comment by Anahit19** [comment]
Dear terhorst,

Thank you for your prompt response!

I would like just to doublecheck if it is ok to have only 16 % of the data indicated in the log file (it is for chromosome 1, for other chromosomes this value varies from 10 to 20%).

Thanks again,

Anahit

**Comment by ShuaishuaiTai** [comment]
Dear Anahit,
I met the same WARNING, do you solve this? Could you please give me some suggestion of this?

Many thanks!
