### ISSUE TITLE
questions about the ancient dna

### ISSUE THREAD

**Issue by Raylc** [popgenmethods/smcpp#152]
Hi @terhorst ! I was wondering if it is possible reconstruct the effective population size history of some ancient populations (low coverage sequence data: x1-x5) using smc++? I know that in your Nature Genetics paper a 45k year old sample was included, but that one has a a pretty decent coverage depth (x42).

**Comment by terhorst** [comment]
SMC++ will run, but the question is whether the results will actually be useful. The lower is your coverage, the less evolutionary signal the data contain, and the harder it will be to accurately infer the size history. You can even see this in (non-ancient) 1kg data, which has a similar average coverage: the estimates turn out pretty coarse, at least to my eye. My recommendation would be to simulate data of similar vintage and quality to what you expect, and first make sure things look reasonable on the simulated data.
