### ISSUE TITLE
about -m mask file

### ISSUE THREAD

**Issue by yinhongwei4079** [popgenmethods/smcpp#156]
@terhorst  I have run smc++ while it have warnings like "147434 smcpp.estimation_tools WARNING Long runs of homozygosity in contig /vol3/agis/likui_group/yinhongwei/05_snp/smcpp/outByChr/chr18.smc.gz". i wonder to know i have to use -m to solove it and if the parameters of "-m" had big effects on the results?  if i have the make the genome mask file, can you recommodes some software except genomecomputmask of genomestrip?

**Comment by terhorst** [comment]
Yes, it can affect then results; see [#2 of the FAQ](https://github.com/popgenmethods/smcpp#frequently-asked-questions) for more information. The genome mask file is expected to be in BED format, so any software that can generate BED files will work. For masking out centromeres and such, I usually just pull the appropriate track from e.g. the UCSC genome browser and edit it by hand. If you have a more complicated mask to apply, I'd recommend using something like [pybedtools](https://daler.github.io/pybedtools/).

**Comment by mayufeifei28** [comment]
Hi yinhongwei4079, which software you finally used to create the mask files? Thanks
