### ISSUE TITLE
Installation errors with conda on Ubuntu 18.04

### ISSUE THREAD

**Issue by lczech** [popgenmethods/smcpp#159]
I'm having trouble getting smcpp to run under Ubuntu 18.04. 

 - First, by just trying to install `smcpp =1.15.3`, I run into the GLIBC error that is explained in the [FAQ](https://github.com/popgenmethods/smcpp#frequently-asked-questions): 
   ```
   ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found
   ```
   This looks like GLIBC 2.29 is required by smcpp 1.15.3. That GLIBC version is available starting from Ubuntu 19.04. As Ubuntu 16 and 18 are still widely in use, I suggest to compile the conda binary with an older GLIBC, if possible, so that it runs on these systems, too.
 - Next, I tried to specify older smcpp versions in conda instead, 1.15.0 to 1.15.2, and get unhelpful conda errors:
   ```
   Found conflicts! Looking for incompatible packages.
   This can take several minutes.  Press CTRL-C to abort.
   failed
   
   UnsatisfiableError: 
   ```
   with no further details after that last line - so, I don't know what went wrong there. I tried updating conda, but that did not help either.
 - So, my next attempt was to build from source instead, but that did not work either. I'll open another issue for that, because these are unrelated errors.

As the GLIBC issue is already explained in the FAQ, I mainly open this issue to ask for a conda binary that uses a more reasonable GLIBC version by default. I want to run smc++ in a cluster environment soon, and these setup issues are really hindering that. 

In particular, it seems that I cannot use conda to install smc++ at all, which makes portability really hard, as then a manual compilation from source is required on the cluster, with a local installation directory, setting up paths, and all that. Basically, with the given requirement to have GLIBC 2.29, the whole conda package seems hardly usable on any but the most recent systems (and in particular on clusters, which are almost never up to date with the latest versions).

Any suggestions welcome!

Thanks
Lucas

**Comment by terhorst** [comment]
Thanks, I will investigate other ways to build the software on older systems. The root cause is that I recently upgraded my OS to Ubuntu 19 :-) In the meantime, you might try using Docker. A user submitted a Dockerfile (#155) precisely to deal with this issue.

**Comment by lczech** [comment]
> Thanks, I will investigate other ways to build the software on older systems. 
Thanks! Maybe building in a VM with an older Ubuntu might work! That's what I do sometimes for my software.

> In the meantime, you might try using Docker. A user submitted a Dockerfile (#155) precisely to deal with this issue.
Thanks again! Hm, so that is a local docker then, or is that available via docker hub as well? I found [this page](https://hub.docker.com/r/terhorst/smcpp), but that does not seem to contain a docker image. The issue for me is that I want to incorporate smc++ in a Snakemake pipeline, which (as far as I am aware) cannot use local images, but needs a docker hub image... So, that would not solve my issue, unfortunately.

**Comment by terhorst** [comment]
I'm in the process of setting up automated Dockerhub builds. It should be ready in a day or two.

**Comment by terhorst** [comment]
Okay, this is set up. A Dockerhub image for HEAD is automatically built and pushed to `terhorst/smcpp:latest` after each commit. I will push a versioned image beginning with v1.16. See README for instructions; it's much easier than before. (Would that Docker was around when I first released this project.)

**Comment by lczech** [comment]
Oh wow, thank you very much, that was an awesome time from request to solution! I'll give the docker image a try soon - that will make setup so much easier! Thanks ;-)
