### ISSUE TITLE
Names of keys in the pickled dictionary object from the 'posterior' command in version 1.8.0 are funky

### ISSUE THREAD

**Issue by ejewett** [popgenmethods/smcpp#16]
Hey Jonathan,

Thanks a bunch for all your help so far! We seem to be getting some nice estimates.

No rush on this one (I think I can solve it with a bit of post-processing as long as I don't run into new issues), but the keys in the pickled dictionary object produced by the posterior command in version 1.8.0 are a bit funky.

In previous versions, the keys are 'sites', 'hidden_states', and 'posterior'. However, it looks like something got messed up during the update to version 1.8.0 and the names are now:

'hidden_states'
'/path/to/input/file_sites'
'/path/to/input/file'

It looks like the correct data are being saved (i.e., '/path/to/input/file_sites' is, in fact, a 'sites' object and '/path/to/input/file' is the 'posterior' object). So I think it's just the names that are weird.

All the best,

Ethan

**Comment by terhorst** [comment]
Yeah I changed this to allow ``smc++ posterior`` to decode more than one contig file at a time. Need to update the docs accordingly.

**Comment by ejewett** [comment]
Okay cool!
