### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by lczech** [popgenmethods/smcpp#161]
In the README, it it stated that Python 3.7 or greater is required. However, when installing in a conda environment with Python 3.8, I get a conflict, telling me that 
`smcpp=1.15.3 -> python[version='>=3.7,<3.8.0a0']` 
is required. Hence, I suggest to adapt the README to state that exactly Python 3.7 is required.

NB: With previous releases of smc++, the required Python version seems to be even more complicated:

 - ```
   Package python conflicts for:
   smcpp=1.15.2 -> python[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
   smcpp=1.15.2 -> ad[version='>=1.3.2'] -> python[version='2.7.*|3.5.*|3.6.*|3.4.*|>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
   python=3.5
   ```
 - ```
   Package python conflicts for:
   python=3.5
   smcpp=1.15.1 -> ad[version='>=1.3.2'] -> python[version='2.7.*|3.5.*|3.6.*|3.4.*|>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
   smcpp=1.15.1 -> python[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
   ```

... after which I gave up. I don't understand the issue here, as the specified python version (3.5) seems to me to fit the requirements listed in these conflict messages. I tried to install these older versions as a workaround to the [GLIBC issue](https://github.com/popgenmethods/smcpp/issues/159#issue-640838446) that I am having with Ubuntu 18.04, but did not get these versions to work, either.

**Comment by terhorst** [comment]
SMC++ runs fine with any version of Python >= 3.7. But some of the packages we depend on do not yet provide builds for Python 3.8 (e.g. pysam-developers/pysam#749). In the past, the same was true for other packages and earlier versions of Python as well.

**Comment by lczech** [comment]
Oh my... welcome to dependency hell... I'm sorry for all the trouble! Well, I'll stick with Python 3.7 then for the time being!
