### ISSUE TITLE
Drop Anaconda support in favor of Docker

### ISSUE THREAD

**Issue by terhorst** [popgenmethods/smcpp#164]
Juggling all of our dependencies, their version requirements, GLIBC/openmp incompatibilities, etc. etc. is proving to be way too complicated (cf. #161, #159, #136, #122, #51, #50, #49, #36, #27). The dependency resolver for `conda build` currently takes over 15 minutes to complete. This is not sustainable. Starting with v1.15.4 we will provide a containerized build using Docker instead.

**Comment by lczech** [comment]
NB: The docker image can be found here: https://hub.docker.com/r/terhorst/smcpp
