### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by yinhongwei4079** [popgenmethods/smcpp#167]
hi @terhorst 
   I run  smc++ for converting my vcf to smc++ files，this is my codes。
for  indiv in `echo Korea:Korea01,Korea02,Korea03,Korea04,Korea05,Korea06|cut -d : -f 2 |tr ',' ' '`
   do
      smc++ vcf2smc -d ${indiv} ${indiv} --mask /vol3/agis/likui_group/yinhongwei/sweep/06_smc/smc_mask/pig_all.mask.bed.gz /vol3/agis/likui_group/yinhongwei/sweep/06_smc/smc.mac1.chr_all.SNP.vcf.gz Korea/${indiv}.chr${i}.smc.gz ${i} Korea:Korea01,Korea02,Korea03,Korea04,Korea05,Korea06
   done
 while  it got errors
2213 smcpp.commands.vcf2smc INFO Population 1:
2214 smcpp.commands.vcf2smc INFO Distinguished lineages: Korea01:0, Korea01:1
2214 smcpp.commands.vcf2smc INFO Undistinguished lineages: Korea02:0, Korea02:1, Korea03:0, Korea03:1, Korea04:0, Korea04:1, Korea05:0, Korea05:1, Korea06:0, Korea06:1
  0%|          | 321k/274M [00:01<15:52, 288kbases/s] 
3471 smcpp.util   INFO Wrote 6419 observations
Traceback (most recent call last):
  File "/vol3/agis/likui_group/yinhongwei/software/miniconda/envs/smcpp/bin/smc++", line 8, in <module>
    sys.exit(main())
  File "/vol3/agis/likui_group/yinhongwei/software/miniconda/envs/smcpp/lib/python3.7/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/vol3/agis/likui_group/yinhongwei/software/miniconda/envs/smcpp/lib/python3.7/site-packages/smcpp/commands/vcf2smc.py", line 255, in main
    abnb = rec2gt(rec)
  File "/vol3/agis/likui_group/yinhongwei/software/miniconda/envs/smcpp/lib/python3.7/site-packages/smcpp/commands/vcf2smc.py", line 173, in rec2gt
    for un in undist]
  File "/vol3/agis/likui_group/yinhongwei/software/miniconda/envs/smcpp/lib/python3.7/site-packages/smcpp/commands/vcf2smc.py", line 173, in <listcomp>
    for un in undist]
  File "/vol3/agis/likui_group/yinhongwei/software/miniconda/envs/smcpp/lib/python3.7/site-packages/smcpp/commands/vcf2smc.py", line 172, in <listcomp>
    if rec.samples[d].alleles[i] is not None]
IndexError: tuple index out of range
  i didn't know why and could you give some adivces?

**Comment by LZeitler** [comment]
This probably happens when missing data is coded '.' instead of './.' (see https://github.com/popgenmethods/smcpp/issues/20#issue-224910947).

You can recode the dataset, e.g., using plink or similar.

**Comment by yinhongwei4079** [comment]
> This probably happens when missing data is coded '.' instead of './.' (see [#20 (comment)](https://github.com/popgenmethods/smcpp/issues/20#issue-224910947)).
> 
> You can recode the dataset, e.g., using plink or similar.

vcftools or bcftools can recde the dataset?

**Comment by LZeitler** [comment]
It probably can, you have to try it. Just look at missing sites if they are coded . before and ./. after then you're good

**Comment by terhorst** [comment]
Thanks for the pointer @LZeitler. @yinhongwei4079 make sure you're using an up-to-date version, I fixed this some time ago in #20 such that you should be getting a more informative error message.

**Comment by yinhongwei4079** [comment]
> Thanks for the pointer @LZeitler. @yinhongwei4079 make sure you're using an up-to-date version, I fixed this some time ago in #20 such that you should be getting a more informative error message.

 I install the smc++  with conda,but when i checked the version of th smc++, it showed SMC++ v1.15.4.dev5+g94b7266.
I  wander to if i had made some mistakes when i installed the smc++ with conda?

**Comment by yinhongwei4079** [comment]
@LZeitler 
i had tried some methods to recode the missing but i failed. would tell me the codes to recode th missing genotypes??

**Comment by LZeitler** [comment]
`plink --vcf foo.vcf --keep-allele-order --recode vcf-iid --out foo.recoded`
https://www.cog-genomics.org/plink/

**Comment by XiaXiaTianTian** [comment]
Hi, @terhorst  and everyone,
I used SMC++ v1.15.5, and checked missing in vcf was coded ./.
But I came into same error `if rec.samples[d].alleles[i] is not None]
IndexError: tuple index out of range`
By the way, surprisingly, I ran sucessesfully in other groups using the same data.
Would you please give some advice?

**Comment by anubhabkhan** [comment]
Hey,
I get a similar error but my missing data is coded as ./.
Can someone please help. 
The command:

smc++ vcf2smc input.recode.vcf.gz HiC_scaffold_1.smc.gz HiC_scaffold_1 SWB:WB_GMG_03,WB_JPK_03,WB_GMD_10,WB_GMM_01,WB_GMG_06

The error message:

Traceback (most recent call last):
  File "/miniconda3/envs/SMCPP/bin/smc++", line 8, in <module>
    sys.exit(main())
  File "/miniconda3/envs/SMCPP/lib/python3.9/site-packages/smcpp/frontend/console.py", line 28, in main
    cmds[args.command].main(args)
  File "/miniconda3/envs/SMCPP/lib/python3.9/site-packages/smcpp/commands/vcf2smc.py", line 255, in main
    abnb = rec2gt(rec)
  File "/miniconda3/envs/SMCPP/lib/python3.9/site-packages/smcpp/commands/vcf2smc.py", line 170, in rec2gt
    bs = [[rec.samples[d].alleles[i] != ref
  File "/miniconda3/envs/SMCPP/lib/python3.9/site-packages/smcpp/commands/vcf2smc.py", line 170, in <listcomp>
    bs = [[rec.samples[d].alleles[i] != ref
  File "/miniconda3/envs/SMCPP/lib/python3.9/site-packages/smcpp/commands/vcf2smc.py", line 172, in <listcomp>
    if rec.samples[d].alleles[i] is not None]
IndexError: tuple index out of range

**Comment by zhaodz980805-cpu** [comment]
Hello, I also encountered this problem recently. Has anyone solved it? I look forward to anyone's reply very much, thank you very much!

**Comment by athenasyarifa** [comment]
Hey everyone, 
I also encountered the same error, and also thought that my missing data are also coded `./.`. However, to make sure, I ran the following code: 
```
while read chr
  do 
    bcftools +check-ploidy $chr.vcf.gz -- -m | awk '{if($5==1) print$0}' >> ploidy_error.txt
  done < chr_list
```
Then, in `ploidy_error.txt` you should get the positions in each chromosome where there are `.` as missing genotype. You would usually get this if you had subset/remove some individuals with all of the ALT allele, and left the remaining individuals in the vcf file that also had this ALT allele to have `.` as missing genotype (I think, somebody please correct me if I'm wrong). 

You can fix the chromosomes vcf file that has the said error using the following: 
```
for chr in $(cut -f 2 ploidy_error.txt | uniq)
  do
    bcftools +fixploidy $chr.vcf.gz -Oz -- -d 2 > fixed.$chr.vcf.gz
    rm $chr.vcf.gz
    mv fixed.$chr.vcf.gz $chr.vcf.gz
    tabix $chr.vcf.gz
  done
```

Hope this helps!
Cheers,
Rifa
