### ISSUE TITLE
problem about running SMC++ on Docker

### ISSUE THREAD

**Issue by 38293649** [popgenmethods/smcpp#171]
Hi, I have encountered a problem when running SMC++ on Docker, while the same vcf.gz file can be successfully processed on another machine which have previously used conda to install SMC++. See the error message below. 
![image](https://user-images.githubusercontent.com/72552037/95561583-867c8880-0a4d-11eb-8c89-932a1f84c90a.png)

**Comment by terhorst** [comment]
Make sure you specify the correct mount option `-v $PWD:/mnt` as part of your Docker command line. See the [README](https://github.com/popgenmethods/smcpp#installation-instructions) for an example.

**Comment by 38293649** [comment]
Thank you for your reply! 
The command "docker run --rm -v $PWD:/mnt terhorst/smcpp:latest" worked, thank you!

All the best



 
From: Jonathan Terhorst
Date: 2020-10-09 22:10
To: popgenmethods/smcpp
CC: 38293649; Author
Subject: Re: [popgenmethods/smcpp] problem about running SMC++ on Docker (#171)
Make sure you specify the correct mount option -v $PWD:/mnt as part of your Docker command line. See the README for an example.
