### ISSUE TITLE
Bad direction in line search

### ISSUE THREAD

**Issue by mlaylwar** [popgenmethods/smcpp#181]
Hi,

When I run the estimate command across 18 chromosomes I receive the following error about bad direction in line search (see below). I know this error has come up in issue #113 but I am unsure whether it pertains to the same problem.

The population that I am modelling has low levels of inbreeding and is known to have experienced population size collapse in the last 100 years. I am including a mapability mask which masks ~10% of the genome, but have not set the -c option given that we expect a recent population size decline.  

2024132 smcpp.optimize.plugins.progress_printer INFO EM iteration 13 of 20...
2024132 smcpp.analysis.base INFO Running E-step
2087427 smcpp.analysis.base INFO E-step completed
2087432 smcpp.optimize.plugins.loglikelihood_monitor INFO New loglik: -3828325.403412	(old: -3828661.864913 [0.008788%])
2087432 smcpp.optimize.plugins.loglikelihood_monitor INFO Log-likelihood improvement < tol=0.0001; terminating

 Bad direction in the line search;
   refresh the lbfgs memory and restart the iteration.

Any idea if there is a way to stop it from aborting?

Thanks

**Comment by terhorst** [comment]
Given that the optimizer seems to have converged by iteration 13, I would first try setting --em-iterations to something lower than that number (say 12) and seeing if it terminates correctly.

**Comment by mlaylwar** [comment]
Yep that seems to work - at least it terminates due to tolerance level below threshold now. 

Does it makes sense to reduce --ftol to get 20 iterations to complete, or better to accept the number of iterations with tolerance at 0.0001? I'm not sure what factors affect whether or not to change that parameter. 

Thanks

**Comment by terhorst** [comment]
I don't have good intuition for which option is better. Does the output
differ substantially?

**Comment by mlaylwar** [comment]
It doesn't change much actually, and even setting it much lower it still terminates early. 

Thanks
