### ISSUE TITLE
cubic spline has a different pattern than default

### ISSUE THREAD

**Issue by selasphoruskershaw** [popgenmethods/smcpp#183]
Hi, 

I've started using SMC++ and am enjoying the program, but have a few questions.

1) When I implement the cubic spline, why does the plot look different than the default graph (both are attached below for the same dataset)? The default graph generally matches the output by msmc2 and psmc, but I don't really understand this cubic spline output.
[borneo_smcpp_spline_cubic (1).pdf](https://github.com/popgenmethods/smcpp/files/6207591/borneo_smcpp_spline_cubic.1.pdf)
[borneo_smcpp (1).pdf](https://github.com/popgenmethods/smcpp/files/6207592/borneo_smcpp.1.pdf)

2) Why do my plots have predictions of 10e-1? Is this a future prediction, or some sort of error?

3) What programs might I use to bootstrap the data so I can plot several different iterations as in msmc2 and psmc?

4) When I run --estimate, intermediate files aren't being stored anywhere. Do I need to specify that I want them saved in addition to the final model.final.json file?

Thank you for your help and sorry about my confusion!

**Comment by Lunasirious** [comment]
> Hi,
> 
> I've started using SMC++ and am enjoying the program, but have a few questions.
> 
> 1. When I implement the cubic spline, why does the plot look different than the default graph (both are attached below for the same dataset)? The default graph generally matches the output by msmc2 and psmc, but I don't really understand this cubic spline output.
>    [borneo_smcpp_spline_cubic (1).pdf](https://github.com/popgenmethods/smcpp/files/6207591/borneo_smcpp_spline_cubic.1.pdf)
>    [borneo_smcpp (1).pdf](https://github.com/popgenmethods/smcpp/files/6207592/borneo_smcpp.1.pdf)
> 2. Why do my plots have predictions of 10e-1? Is this a future prediction, or some sort of error?
> 3. What programs might I use to bootstrap the data so I can plot several different iterations as in msmc2 and psmc?
> 4. When I run --estimate, intermediate files aren't being stored anywhere. Do I need to specify that I want them saved in addition to the final model.final.json file?
> 
> Thank you for your help and sorry about my confusion!

Hey did you figure it out why it's different? I am having the same issue here
