### ISSUE TITLE
Expected results for example vcf and composite likelihood

### ISSUE THREAD

**Issue by Neato-Nick** [popgenmethods/smcpp#186]
Hi, I'm enjoying learning to use smc++

I'm starting with the example data. Is there a known true biological history for this that we're aiming to see? I get different histories using [composite likelihoods](https://github.com/popgenmethods/smcpp/files/6368759/plot.complikelihood_msp0-4_1pop.mc500.pdf) versus [the default case](https://github.com/popgenmethods/smcpp/files/6368762/plot.chr1.msp0-4.1pop.mc500.pdf). In both cases I see expansion -> contraction -> expansion, but the composite likelihood shows an older expansion and a prolonged period of contraction instead of a sudden collapse I see using the default parameters. What's going on here, is the composite likelihood more accurate?

```
## Default case
smc++ vcf2smc --missing-cutoff 500 example.vcf.gz out/chr1.msp0-4.1pop.mc500.smc.gz 1 Pop1:msp_0,msp_1,msp_2,msp_3,msp_4
smc++ estimate --cores 6 -o analysis_msp0-4_1pop_mc500/ 1.25e-8 out/chr1.msp0-4.1pop.mc500.smc.gz
smc++ plot plot.chr1.msp0-4.1pop.mc500.pdf analysis_msp0-4_1pop_mc500/model.final.json

## Composite likelihood
for i in {0..2}; do
	smc++ vcf2smc --missing-cutoff 500 -d msp_$i msp_$i example.vcf.gz out/complikelihood_$i.msp0-4.1pop.mc500.smc.gz 1 Pop1:msp_0,msp_1,msp_2,msp_3,msp_4
done
smc++ estimate --cores 6 -o analysis_complikelihood_msp0-4_1pop_mc500/ 1.25e-8 out/complikelihood_*.msp0-4.1pop.mc500.smc.gz
smc++ plot plot.complikelihood_msp0-4_1pop.mc500.pdf analysis_complikelihood_msp0-4_1pop_mc500/model.final.json
```

**Comment by terhorst** [comment]
We only distribute the example VCF to show how to run the program in the docs. It is really tiny, containing just 1Mb of simulated sequence data, so the estimates will depend heavily on various modeling choices that are made. For the use-case that SMC++ targets (genomewide data from 100s of samples), they should be more robust; to get a better sense, I'd recommend simulating a quantity of data that more closely resembles your situation, and then re-running this experiment.

**Comment by Neato-Nick** [comment]
Ah, thanks for the info, I'll try that then. Thanks for distributing that tiny vcf, it's been helpful to play with while going through the documentation

**Comment by terhorst** [comment]
Closing as I think this has been resolved. Please feel free to re-open if you encounter other issues. Thanks!
