### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by biozzq** [popgenmethods/smcpp#2]
Hi @terhorst 

I think it is difficult for me to install this software smoothly. I have stayed here for a long time when I compile `smcpp` from source. The error information like following, The version of GCC is 4.8.5.

`gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/stor9000/apps/users/NWSUAF/2015060152/bin/Python3.5/lib/python3.5/site-packages/numpy/core/include -Iinclude -Iinclude/eigen3 -I/usr/local/include -I/stor9000/apps/users/NWSUAF/2015060152/bin/Python3.5/include/python3.5m -c smcpp/_smcpp.cpp -o build/temp.linux-x86_64-3.5/smcpp/_smcpp.o -O2 -std=c++11 -Wno-deprecated-declarations -DNO_CHECK_NAN -fopenmp
In file included from /stor9000/apps/users/NWSUAF/2015060152/bin/Python3.5/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:0,
                 from /stor9000/apps/users/NWSUAF/2015060152/bin/Python3.5/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /stor9000/apps/users/NWSUAF/2015060152/bin/Python3.5/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from smcpp/_smcpp.cpp:509:
/stor9000/apps/users/NWSUAF/2015060152/bin/Python3.5/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" `[-Wcpp]`
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from include/common.h:12:0,
                 from smcpp/_smcpp.cpp:501:
include/mpreal.h: In member function ‘float mpfr::mpreal::toFloat(mpfr_rnd_t) const’:
include/mpreal.h:1723:115: error: ‘mpfr_get_flt’ was not declared in this scope
 inline float              mpreal::toFloat  (mp_rnd_t mode)  const    {    return  mpfr_get_flt(mpfr_srcptr(), mode);    }
                                                                                                                   ^
error: command 'gcc' failed with exit status 1`

Hope your help
Best
Zhuqing

**Comment by terhorst** [comment]
The missing function was added to ``libmpfr`` in version 3, so this indicates that the version of ``libmpfr`` in your machine is too old. To fix this error, update the library to a more recent version. Alternatively, if you are on a supported platform (Linux or Mac) I recommend using the pre-built binaries we provide (see the README).

**Comment by biozzq** [comment]
Hi @terhorst 

Thanks, I will have a try.

Best
