### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by hrazif** [popgenmethods/smcpp#20]
I was running into this error while trying to convert my VCF file to SMC++ input format. Jonathan kindly pointed out that the error was caused by values for missing data ("."), which should be coded as "./." for SMC++ to recognize. 

I changed the coding for the missing data to "./." and was able to convert my file. 

Thanks Jonathan!

**Comment by mishaploid** [comment]
I am also running into this error, but only when the vcf file is very large (i.e. when I reduce the number of samples the conversion works well). 

hrazif, would you mind sharing how you converted missing data in the vcf from "." to "./."? 

Thank you in advance for any advice!
