### ISSUE TITLE
Time scale

### ISSUE THREAD

**Issue by pssantos** [popgenmethods/smcpp#22]
Hi,
I am learning how to use the smc++. I started for analyzing two populations (and using only two individuals for each population). When I used the version 1.7.0 of the program I was able to plot a recent time of 1000 years ago (I use a generation time of 25 years to convert the scale from coalescent time to calendar time). However, in the newest version (1.8.0) the most recent time is approximately 25000 years ago.
Why I cannot reach the same times as in the paper (most recent time = 1000 years ago)? 
Could you give me some advice to improve my analysis?
I used the commands described in the quick start guide.
Thanks in advance.
Best regards,
Patricia

**Comment by terhorst** [comment]
Hi Patricia, yeah, I changed the default behavior to adapt the most recent time interval to the sample size. For small sample sizes the estimated size history is not reliable in the very recent past (e.g. 1kya), so in v1.8 it sets it to be further back in time. You can control the placement of the most recent time interval using the ``--t1`` option (see [tips](https://github.com/popgenmethods/smcpp/blob/master/README.rst#tips-for-using-smc)) but if the number of individuals is small, you should be careful not to set this too low.

**Comment by pssantos** [comment]
Thank you for your help.
