### ISSUE TITLE
Error of SMC++

### ISSUE THREAD

**Issue by jlugxs** [popgenmethods/smcpp#23]
I downloaded the SMC++ program (Version 1.8.0) yesterday and installed it successfully. However, when I run it on Linux command line, it reports an error of "Segmentation fault". How can I fix this error?
Thanks.

**Comment by terhorst** [comment]
Could you please produce a stack trace as described in #21, I think this might be the same issue. Thanks

**Comment by terhorst** [comment]
Could you please try the [latest release](https://github.com/popgenmethods/smcpp/releases/latest) and let me know if this still happens?

**Comment by terhorst** [comment]
Closing as this appears to be fixed (cf #21).
