### ISSUE TITLE
Build failed in Python 3.11

### ISSUE THREAD

**Issue by tcztzy** [popgenmethods/smcpp#240]
When I follow the README `pip install git+https://github.com/popgenmethods/smcpp`, it throw out error following.
```
smcpp/_smcpp.cpp:196:27: fatal error: longintrepr.h: No such file or directory
   #include "longintrepr.h"
                           ^
compilation terminated.
```

The following URLs may explain the cause.

https://github.com/aio-libs/aiohttp/issues/6600
https://github.com/cython/cython/pull/4428

**Comment by terhorst** [comment]
Thanks for reporting. I'm able to build SMC++ on Python 3.11 on my machine now, so I assume Cython fixed this bug upstream.

**Comment by aguilar-gomez** [comment]
I am getting this error in Python 3.12.0

**Comment by mufernando** [comment]
I am also getting this error on Python 3.12.3

**Comment by r-poloni** [comment]
I am trying to build in a computing cluster, so I created a conda environment with all the packages listed (python, gmp, etc.) and then ran python setup.py install and is throwing the same error. With pip it didn't work either. Do you have any solution to install it on a computing cluster?

**Comment by Gullumluvl** [comment]
Same issue here with master or devel branch:

I start from a fresh environment with `micromamba`:

    micromamba create -n test_smcpp mpfr gsl python=3.11 numpy
    micromamba activate test_smcpp
    pip install git+https://github.com/popgenmethods/smcpp

- with Python >= 3.11: missing `longintrepr.h`

- with Python <= 3.10: cannot find `-lmpfr` and `-lgmp` and `-lgmpxx` (in `compiler_compat/ld)`. Any global variable we can set to fix this?

**Comment by jamoroso8** [comment]
Hi, I am still getting this same error using Python 3.11 conda envrionment on a computing cluster, wondering if anyone found a workaround?
