### ISSUE TITLE
Can SMC++ analyze samples collected at different sampling times?

### ISSUE THREAD

**Issue by XiaoleLei** [popgenmethods/smcpp#249]
Hi, 

So excellent software!
And I'm wondering if it can be used to analyze samples collected at different sampling times. For instance, if I have a group that includes one sample from 10,000 years ago and another from 20,000 years ago, can I utilize this remarkable software for analysis? If so, how should I configure the software parameters?
Thanks.

Best.
Xiaole

**Comment by terhorst** [comment]
Unfortunately, this is not currently supported.
