### ISSUE TITLE
RuntimeError: Hidden states must be in ascending order with hs[0]=0 and hs[-1] = infinity

### ISSUE THREAD

**Issue by nsmackler** [popgenmethods/smcpp#28]
I finally got the program up and running on my new cluster and have run into this error when using "estimate":
"RuntimeError: Hidden states must be in ascending order with hs[0]=0 and hs[-1] = infinity"

It looks like we have lots of runs of homozygosity (probably due to low coverage in some of the samples). Could this be affecting the error? Also, do you have any recommendations for the "depth" argument in the vcf2smc command that might help fix this? We have 218 samples, most of which have coverage of 1-2x (~40 samples are at ≥10x).

Here is the full, verbose debug output:
14804 smcpp.logging DEBUG SMC++ v1.9.3.dev3+g5a93362
14832 smcpp.commands.command DEBUG ['/usr/lusers/nsmack/anaconda3/bin/smc++', 'estimate', '-vv', '-o', '/gscratch/csde/SMackLab//analysis/chr1', '1.25e-8', '/gscratch/csde/SMackLab//chr1.smc.gz']
14832 smcpp.commands.command DEBUG Namespace(algorithm='L-BFGS-B', blocks=None, command='estimate', data=['/gscratch/csde/SMackLab//chr1.smc.gz'], em_iterations=20, ftol=0.0001, knots=10, length_cutoff=10000, mu=1.25e-08, no_filter=False, no_initialize=False, nonseg_cutoff=None, offset=0.0, outdir='/gscratch/csde/SMackLab//analysis/chr1', polarization_error=0.5, r=None, regularization_degree=2, regularization_penalty=7, spline='pchip', t1=None, tK=None, thinning=None, unfold=False, verbose=2, xtol=0.1)
14834 smcpp.analysis DEBUG Polarization error p=0.500000
14834 smcpp.analysis DEBUG regularization degree=2
14834 smcpp.analysis INFO Loading data...
16032 smcpp.analysis INFO 0.23 Gb of data
16033 smcpp.analysis DEBUG Contig(pid=('cayo',), fn='/gscratch/csde/SMackLab//chr1.smc.gz', n=array([434]), a=array([2]))
16034 smcpp.analysis INFO 1 population
23873 smcpp.analysis DEBUG Empirical CSFS:
{(3, 435): array([[224042657,         0,         0, ...,         0,         0,         0],
       [        0,         0,         0, ...,         0,         0,         0],
       [        0,         0,         0, ...,         0,         0,         0]])}
23982 smcpp.estimation_tools WARNING Long runs of homozygosity in contig /gscratch/csde/SMackLab//chr1.smc.gz: 
[[175427      0      0    434]
 [122483      0      0    434]]
24084 smcpp.analysis DEBUG Heterozygosity: 0.003975
24084 smcpp.analysis DEBUG Average heterozygosity (derived / total bases) by data set (* = dropped)
24084 smcpp.analysis DEBUG /gscratch/csde/SMackLab//chr1.smc.gz:
24084 smcpp.analysis DEBUG               0      225584828      225584829  0.00397518
24085 smcpp.analysis INFO theta: 0.000100
24085 smcpp.analysis INFO rho: 0.000100
24085 smcpp.analysis INFO Thinning...
60606 smcpp.analysis DEBUG Ne: 0.000446
60607 smcpp.analysis DEBUG setting t1=200.000004
60607 smcpp.analysis DEBUG setting tK=10.981177
60608 smcpp.analysis DEBUG knots in coalescent scaling:
[ 0.025       0.0187026   0.01399148  0.01046708  0.00783047  0.005858    0.00438239  0.00327849  0.00245265  0.00183484
  0.00137265  0.00274529  0.00549059]
60608 smcpp.analysis DEBUG Long term avg. effective population size: 19.875893
60609 smcpp.analysis DEBUG Creating inference manager...
60609 smcpp.analysis DEBUG Creating inference manager for (('cayo',), (434,), (2,))
60618 smcpp._smcpp:src/matrix_cache.cpp:62 DEBUG1 Acquired lock in init_cache()
60628 smcpp._smcpp:src/matrix_cache.cpp:74 DEBUG1 init_cache() successful
65569 smcpp._smcpp:src/inference_manager.cpp:236 DEBUG1 parallel filling targets
65740 smcpp._smcpp:src/inference_manager.cpp:252 DEBUG1 reducing targets
65750 smcpp._smcpp:src/inference_manager.cpp:53 DEBUG1 creating HMM
66508 smcpp.analysis INFO Running E-step
66508 smcpp._smcpp:src/inference_manager.cpp:108 DEBUG1 E step
66509 smcpp._smcpp:src/conditioned_sfs.cpp:88 DEBUG1 compute called
66515 smcpp._smcpp:src/conditioned_sfs.cpp:47 DEBUG1 compute above
76138 smcpp._smcpp:src/conditioned_sfs.cpp:15 DEBUG1 compute below
76138 smcpp._smcpp:src/conditioned_sfs.cpp:20 DEBUG1 tjj_double_integral below starts
76138 smcpp._smcpp:src/piecewise_constant_rate_function.cpp:304 DEBUG1 in tjj_double_integral_below
76445 smcpp._smcpp:src/piecewise_constant_rate_function.cpp:332 DEBUG1 exiting tjj_double_integral_below
76445 smcpp._smcpp:src/conditioned_sfs.cpp:24 DEBUG1 tjj_double_integral below finished
76445 smcpp._smcpp:src/conditioned_sfs.cpp:25 DEBUG1 matrix products below (M0)
76452 smcpp._smcpp:src/conditioned_sfs.cpp:27 DEBUG1 matrix products below (M1)
76459 smcpp._smcpp:src/conditioned_sfs.cpp:29 DEBUG1 filling csfs_below
76459 smcpp._smcpp:src/conditioned_sfs.cpp:37 DEBUG1 compute below finished
76459 smcpp._smcpp:src/conditioned_sfs.cpp:95 DEBUG1 compute finished
76459 smcpp._smcpp:src/inference_manager.cpp:407 DEBUG1 recompute B
76479 smcpp._smcpp:src/inference_manager.cpp:470 DEBUG1 recompute done
76479 smcpp._smcpp:src/transition.cpp:335 DEBUG1 computing transition
76494 smcpp._smcpp:src/transition.cpp:337 DEBUG1 done computing transition
76505 smcpp._smcpp:src/hmm.cpp:52 DEBUG1 forward algorithm (HMM #0)
76584 smcpp._smcpp:src/hmm.cpp:61 DEBUG1 hmm 0: 9%
76665 smcpp._smcpp:src/hmm.cpp:61 DEBUG1 hmm 0: 19%
76745 smcpp._smcpp:src/hmm.cpp:61 DEBUG1 hmm 0: 29%
76825 smcpp._smcpp:src/hmm.cpp:61 DEBUG1 hmm 0: 39%
76905 smcpp._smcpp:src/hmm.cpp:61 DEBUG1 hmm 0: 49%
76986 smcpp._smcpp:src/hmm.cpp:61 DEBUG1 hmm 0: 59%
77066 smcpp._smcpp:src/hmm.cpp:61 DEBUG1 hmm 0: 69%
77147 smcpp._smcpp:src/hmm.cpp:61 DEBUG1 hmm 0: 79%
77228 smcpp._smcpp:src/hmm.cpp:61 DEBUG1 hmm 0: 89%
77307 smcpp._smcpp:src/hmm.cpp:61 DEBUG1 hmm 0: 99%
77307 smcpp._smcpp:src/hmm.cpp:98 DEBUG1 backward algorithm (HMM #0)
78415 smcpp.analysis INFO E-step completed
78416 smcpp._smcpp:src/inference_manager.cpp:115 DEBUG1 InferenceManager::Q
78416 smcpp._smcpp:src/hmm.cpp:153 DEBUG1 HMM::Q
78423 smcpp._smcpp:src/inference_manager.cpp:125 DEBUG1 
q1:0 []
q2:-3.28873e+06 []
q3:0 []

78423 smcpp._smcpp DEBUG im((('cayo',), (434,), (2,))).q1: 0.0
78424 smcpp._smcpp DEBUG im((('cayo',), (434,), (2,))).q2: -3288734.5
78424 smcpp._smcpp DEBUG im((('cayo',), (434,), (2,))).q3: 0.0
78426 smcpp.analysis DEBUG reg: 0.0 []
78426 smcpp.analysis DEBUG Q:   -3288734.5 []
78426 smcpp.analysis DEBUG Auto-assigning regularization penalty lambda=0.328873
78427 smcpp.analysis DEBUG hidden states: [ 0.          0.025       0.0187026   0.01399148  0.01046708  0.00783047  0.005858    0.00438239  0.00327849  0.00245265
  0.00183484  0.00137265  0.00274529  0.00549059         inf]
78430 smcpp.analysis DEBUG knots in coalescent scaling:
[ 0.025       0.0187026   0.01399148  0.01046708  0.00783047  0.005858    0.00438239  0.00327849  0.00245265  0.00183484
  0.00137265  0.00274529  0.00549059]
78430 smcpp.analysis DEBUG Long term avg. effective population size: 19.875893
78431 smcpp.analysis DEBUG Creating inference manager...
78470 smcpp.analysis DEBUG Creating inference manager for (('cayo',), (434,), (2,))
78478 smcpp._smcpp:src/matrix_cache.cpp:62 DEBUG1 Acquired lock in init_cache()
78484 smcpp._smcpp:src/matrix_cache.cpp:74 DEBUG1 init_cache() successful
Traceback (most recent call last):
  File "/usr/lusers/nsmack/anaconda3/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.9.3.dev3+g5a93362', 'console_scripts', 'smc++')()
  File "/usr/lusers/nsmack/anaconda3/lib/python3.6/site-packages/smcpp/frontend/console.py", line 23, in main
    cmds[args.command].main(args)
  File "/usr/lusers/nsmack/anaconda3/lib/python3.6/site-packages/smcpp/commands/estimate.py", line 65, in main
    analysis = Analysis(args.data, args)
  File "/usr/lusers/nsmack/anaconda3/lib/python3.6/site-packages/smcpp/analysis.py", line 327, in __init__
    self._init_inference_manager(args.polarization_error)
  File "/usr/lusers/nsmack/anaconda3/lib/python3.6/site-packages/smcpp/analysis.py", line 209, in _init_inference_manager
    key, polarization_error)
  File "smcpp/_smcpp.pyx", line 301, in smcpp._smcpp.PyOnePopInferenceManager.__cinit__ (smcpp/_smcpp.cpp:8717)
  File "smcpp/_smcpp.pyx", line 139, in smcpp._smcpp._PyInferenceManager.__my_cinit__ (smcpp/_smcpp.cpp:5458)
RuntimeError: Hidden states must be in ascending order with hs[0]=0 and hs[-1] = infinity

**Comment by terhorst** [comment]
Could you attach ``chr1.smc.gz``? The log seems to indicate that there are no singletons or doubletons in your data, so something is amiss. (Did you filter on MAF?) The error is occuring because the heuristic the program uses to calculate the time span in your model depends on Watterson's estimator, which is extremely low due to the missing mutations.

Out of curiosity, what finally enabled you to get it working?

**Comment by nsmackler** [comment]
Sure thing. Here it is. The error happens with all chromosomes, so I'm assuming it is just something simple that I am messing up. The command I'm using to generate the smc.gz files is:
smc++ vcf2smc ./cayo.rheMac8.ann.vcf.gz ./chr1.smc.gz chr1 cayo:25P,00O,00V,01K,03J,04I,04T,04Z,07D,0A2,0A4,0A9,0B4,0B6,0C6,0D3,0F6,0G9,0I5,10S,12O,14I,14L,17C,17K,17L,18Z,19A,19T,1A3,1A6,1B0,1B1,1C0,1C2,1C5,1E2,1E3,1E5,1E6,1F2,1F9,20F,20S,21N,22H,24B,24V,25L,26P,28B,28J,29B,29V,29Z,2A2,2A5,2A7,2A8,2C3,2C4,2C8,2C9,2D5,2F0,2F2,2F9,2G2,30C,30L,31S,32S,33T,33V,34N,34P,35N,35V,36T,36Z,37N,37V,3A9,3B9,3D9,3E2,3E4,3F4,40L,42L,42T,43F,43H,43J,43N,43P,44J,46N,46Z,47Z,48V,4A9,4C1,4C3,4C5,4D3,4D8,4G8,50S,51V,52P,52Z,53E,53Z,54N,55J,55V,56E,56K,57F,57H,59A,5B0,5B2,5C0,5E1,5E4,5E8,5G7,60E,60P,60R,60T,61D,61J,61R,62R,63V,64D,64P,64S,68V,6A8,6B2,6C0,6C2,6C5,6D4,6D6,6D9,6F2,6F6,72T,73V,73Z,74S,77I,78I,78T,79Z,7B2,7B3,7B7,7C0,7D7,7D8,7F0,7F5,80S,80T,81I,82A,82L,85B,85T,86Z,88I,88N,88T,8B0,8B5,8C0,8C9,8D6,8E8,8F3,91V,92D,93O,93Z,94H,96B,98T,98Z,99L,9A4,9C1,9C2,9C5,9C6,9D4,9D8,9E3,9E5,9E6,9E8,9F5,9H7,9H9,K00,N12,O34,O52,T84,V36,X44,X58,Z46

[chr1.smc.gz](https://github.com/popgenmethods/smcpp/files/1039607/chr1.smc.gz)

And I was able to get it working by doing the following (installing using conda):
## Install the newest version of Anaconda in some location, below represented by $APYTHON
node$ . /opt/rh/devtoolset-2/enable  ## enable CentOS
node$ export CPPFLAGS="-I$APYTHON/include"
node$ export PATH=$APYTHON/bin:$PATH
node$ conda install mpfr gsl gmp
node$ pip install git+https://github.com/popgenmethods/smcpp
node$ smc++ -h

Then it worked like a charm. 

Thanks for your help.

**Comment by terhorst** [comment]
Could you try rebuilding from master? The error was caused by the way I was calculating Watterson's estimator -- instead of doing the proper thing and taking the MCLE the entire data set, I had restricted only to sites which had no missing data. In your data, almost all such sites are monomorphic, so the estimate was coming out extremely low. I've fixed the computation of theta, but you may want to check the calls are what you expect.
