### ISSUE TITLE
singletons, include or exclude?

### ISSUE THREAD

**Issue by hrazif** [popgenmethods/smcpp#29]
Hello all.

I have noticed that when I exclude singletons (SNPs present only in one individual) from my datasets, the population history estimate is different from when I include them. Considering that singletons are usually filtered out as a quality control criterion, I wonder whether it is important for SMC++ to keep them.

I would appreciate your help.

**Comment by terhorst** [comment]
The results would definitely be different since singletons are, on average, the most common type of mutation and are informative of recent size history. So it is important to keep them. SMC++ assumes that the data has not been filtered on the basis of mutation frequency.
