### ISSUE TITLE
The parameters about vcf2smc mask

### ISSUE THREAD

**Issue by biozzq** [popgenmethods/smcpp#3]
Hi @terhorst 

Thanks for your update on the installation. `smcpp` was successfully installed on my server. But when I have a look at the parameters about ` vcf2smc` , I can not fully know how to generate the mask file in bed format. I have once run `MSMC2` and generated the mask file for each individual using his script called `bamCaller.py`, but I do not know how to generate these files based on population information. Can I just merge the files from `bamCaller.py` in one population and use the merged mask files (also integrated the mapping ability mask file) to run `vcf2smc`?

Moreover, If I want to get more information in recent years, how many individuals and how can I select proper individuals (maybe something about the heterozygous SNPs pattern)  to go to computation process? I hope you can share us some experience about these which can help us run `smcpp` smoothly.

Best
Zhuqing

**Comment by terhorst** [comment]
Hi,

The ``--mask`` option in ``vcf2smc`` is designed to apply a BED-formatted mask file uniformly across all samples, with the idea of filtering out large uncallable regions (i.e. centromeres). The saves you the trouble of writing out millions of rows of missing observations in the VCF. Individual-specific BED files are not currently supported. Instead, you should mark those positions as missing in the VCF, and then use ``vcf2smc``.

Regarding your second question, "recent years" depends on what you are studying. For humans we were able to get reasonable results in our paper using panels of 100-200 individuals per population. You should *not* pick and choose distinguished individuals based on heterozygosity, as this would lead to ascertainment bias. Instead, select a few individuals at random for forming the composite likelihood. In our analysis we used six, and this provided a good tradeoff between accuracy and computational demands. (Unfortunately we don't have any theory at the moment to guide this choice.) Note that the memory and computation requirements scale linearly in the number of distinguished individuals, assuming you generate a complete set of chromosome data for each one of them.
