### ISSUE TITLE
Composite likelihood over different distinguished individuals

### ISSUE THREAD

**Issue by JiangYuLab** [popgenmethods/smcpp#31]
Dear @terhorst 
Maybe the different distinguished individuals can lead to different results, from your recommendation,  I can use composite likelihood  to improve our results. But during the process, I have some questions about the input files of the `estimate`. According to your example, I will create three data sets from contig `chr1` (like following), should I pass all these three files to `estimate` together? If so, my species have 29 chromosomes, If I have used ten different distinguished individuals, it will have 290 input files for `estimate`,  is this right? 
````
for i in {7..9};
    do smc++ vcf2smc -d NA1287$i NA1287$i myvcf.gz out.$i.txt chr1 NA12877 NA12878 NA12879
done
````
Thanks
Best
Zhuqing

**Comment by terhorst** [comment]
That's correct.

**Comment by JiangYuLab** [comment]
Dear @terhorst 

From your previous comments #30 ,  you recommend parametric bootstrap to assess uncertainty in the recent past. Maybe by breaking up the genome into small chunks and resampling, which has the advantage of keeping the sample size the same is a best choice. But I can not find some information about doing bootstrap like this.  Can you give me some details about how to realize it or write a section about bootstrap in the readme? Thank you.

Best
Zhuqing

**Comment by elizeng** [comment]
I have the same question, once the smc++ vcf2smc step is done, do you use all 290 input files for estimate at one go?

It is the next logical step to use all 290 output files from vcf2smc for estimate, but wanted to check with everyone on here.
