### ISSUE TITLE
libgomp: Thread creation failed

### ISSUE THREAD

**Issue by songli-bgi** [popgenmethods/smcpp#33]
Hi,

I used "smc++ estimate" to estimate effect population size of human. The virtual memory size will become enormous, and it grew bigger as program running. At the end, the program crashed with the error:
libgomp: Thread creation failed: Resource temporarily unavailable
What is wrong? Was anyone meet this problem before?

Best
Song Li

**Comment by terhorst** [comment]
I need to know more about your setup to help you troubleshoot this. Please [consult the README](https://github.com/popgenmethods/smcpp/blob/master/README.rst#what-to-do-if-you-encounter-trouble).
