### ISSUE TITLE
Infomation on N_0

### ISSUE THREAD

**Issue by cteenis** [popgenmethods/smcpp#4]
Hi,

Thank you so much for this software and I'm eager to try it (trying now actually).
I want to run the estimate specifying --rho and --theta, which, according to the README file, is  2 N_0 r and  2 N_0 \mu, I can calculate mu and r from literature but what value of N_0 should I use in this case? Is it "2 * the number of individuals included in the analysis"?

**Comment by terhorst** [comment]
N0 is just a scaling factor; it's really only used for plotting. Unless you expect your population to have a very large expected population size (drosphila, for example) you can leave it set to the default value of 10^4 and specify the mutation rate accordingly.
