### ISSUE TITLE
How to use plot function with offsets

### ISSUE THREAD

**Issue by LindoAncient** [popgenmethods/smcpp#40]
Hello,

I'd like to use the offset feature to plot ancient samples that are about 2000 years old. How do I use the -t option in plot to shift the x axis? I can't seem to find command-line instructions on this feature. 

Thank you,

John

**Comment by terhorst** [comment]
It takes a space-separated list of offsets given in calendar years. There must be exactly as many offsets as there are ``model.final.json`` files passed in. Models which start at the present should be assigned the value ``0``.
