### ISSUE TITLE
How can we provide more quantitative insight about Ne in recent time?

### ISSUE THREAD

**Issue by biozzq** [popgenmethods/smcpp#41]
Dear @terhorst 

In order to assess uncertainty in the recent past, I have done bootstrap by breaking up the genome into small chunks and resampling.  But I found the results is big different in recent time when I used different distinguished individuals.  Can you give us some suggestions to improve the results? Thanks.

![image](https://user-images.githubusercontent.com/15704257/30594281-19d51eb4-9d80-11e7-9a15-8b97b1fe116f.png)

Best
Zhuqing

**Comment by terhorst** [comment]
I'd recommend combining all distinguished individuals into one composite likelihood, and bootstrapping that. Also the most recent version (1.10.0) has some improvements that may reduce the variance somewhat.
