### ISSUE TITLE
File format for split analysis

### ISSUE THREAD

**Issue by melop** [popgenmethods/smcpp#44]
Hello,

I am confused about the file format containing the joint frequency spectrum for the split analysis. 

```
$ smc++ vcf2smc my.vcf.gz data/pop12.smc.gz <contig> pop1:ind1_1,ind1_2 pop2:ind2_1,ind2_2
$ smc++ vcf2smc my.vcf.gz data/pop21.smc.gz <contig> pop2:ind2_1,ind2_2 pop1:ind1_1,ind1_2

```

Currently the workflow described in README requires producing two separate smc files if one wants to perform the split analysis. The distinguished individual from Pop1 is used in file 12 while the distinguished individual from Pop2 is used in file 21. From testing the command, it looks like column 5 is simply left as 0's. 

When I read the description input file format, however, there seems to be a possibility of coding both distinguished individuals in one file (on columns 2 and 5, respectively). 

I'm wondering about the reason to produce two separate files for the split analysis. Is it possible to just use a single file?

To be clear I am writing my own script to convert directly to the smc format, by-passing the vcf2smc command.

Best Regards,
Ray

**Comment by terhorst** [comment]
The sum of columns 2 & 5 must be <= 2. (Exactly two haploid lineages are treated as distinguished.) So you really need one file per distinguished individual. In the case where both lineages originate in the same population column 5 will always be zero. If you have phased data it is technically possible to pull one lineage from both population, in which case 2 and 5 will be no more than 1. 

I'd strongly recommend using ``vcf2smc`` if at all possible.

**Comment by melop** [comment]
Thanks for the clarification. The reason why vcf2smc doesn't work for us is because we estimated allele frequencies and the number of effectively sampled chromosomes using Package-GFE https://github.com/Takahiro-Maruki/Package-GFE from individuals of low coverage, while the distinguished individual has higher coverage from which we can call genotype.
