### ISSUE TITLE
smc++ estimate uses huge numbers of processes/threads during startup

### ISSUE THREAD

**Issue by grahamgower** [popgenmethods/smcpp#46]
It would appear that `smc++ estimate` forks a large number of processes at startup - one for each cpu core. Further, each of these processes starts a thread of execution for each cpu core (or maybe something else is going on with the forkserver(s), I didn't try to understand the code concretely). After the EM analyses actually begins proper, the processes complete and all is well again. We have 72 cpu cores on our main compute node, which means a spike of 72*72=5184 threads during startup. The spike lasts less than a minute.

Actually, once the EM procedure starts, smc++ estimate seems to use only 1 thread for each contig/input file. So running multiple concurrent invocations of `smc++ estimate` on different datasets is still reasonable on our system. I can bump the user process limit up, with `ulimit -u $(ulimit -Hu)` and this allows me to overcome the huge number of 'user processes' at startup.

Perhaps there is a simple change that can fix the behaviour at startup? Surely the large number of context switches actually makes the parallelisation at startup counter productive, at least in the case of a large number of cores.

**Comment by terhorst** [comment]
The default behavior is to use all cores. Unless your system is very restrictive I don't see why launching one process per core would run up against ulimits...?  Anyways, I can add a ``--cores`` command to control that it. Threading would be controlled by the enviornment variable ``OMP_NUM_THREADS``. Regarding the threads issue, I think what's happening is each forkserver worker instance is creating its own OpenMP thread pool upon loading ``smcpp._smcpp``. Probably this behavior changed when I switched from fork to forkserver. This is a bit wasteful but it should not result in more than one thread (the main Python thread) executing at once. So the total usage should just be all cores, not (all cores)^2.

**Comment by grahamgower** [comment]
Our default soft limit for ulimit -u is 1024, which is hit during `smc++ estimate`. I'm not sure precisely what causes this. I did not notice any problems before the recent changes, so perhaps there is something in the forkserver change.

**Comment by terhorst** [comment]
Unbeknownst to me, threads = processes in the eyes of ulimit, at least on Linux. So that explains it. Working on a fix now.

**Comment by harlydurbin** [comment]
Before I submit a redundant issue, wondering if my problem is related. 
Originally, I was encountering the error referenced in  https://github.com/popgenmethods/smcpp/issues/39 . Upon updating, I've started getting the following error during `smc++ estimate`:  
`Traceback (most recent call last):
  File "/home/hjdzpd/miniconda3/envs/snake/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.10.0', 'console_scripts', 'smc++')()
  File "/home/hjdzpd/miniconda3/envs/snake/lib/python3.6/site-packages/smcpp/frontend/console.py", line 22, in main
    mp.set_start_method('forkserver')
  File "/home/hjdzpd/miniconda3/envs/snake/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
`
The [debug.txt](https://github.com/popgenmethods/smcpp/files/1369684/debug.txt) file is attached.
Thanks for your help!
Harly

**Comment by terhorst** [comment]
@harlydurbin I can't reproduce this error using Python 3.6 on my machine. How did you install or build the software?
