### ISSUE TITLE
Installation error with pip install 

### ISSUE THREAD

**Issue by cooken1** [popgenmethods/smcpp#48]
After following the build instructions, running the `pip install git+https://github.com/popgenmethods/smcpp` command leaves me with a fatal error:

```
> 
> home/user/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-3y7c2c4g-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);
> 	code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-js3mxwwh-record/install-record.txt 
> 	--single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-3y7c2c4g-build/
```

Alternative efforts with just the `conda` command have encountered the `GLIBCXX_3.4.21 not found` mentioned in the FAQ. 

Any advice to help properly install would be much appreciated.

**Comment by terhorst** [comment]
I've not tried installing via ``pip`` from within a Conda environment. Conda and ``pip`` have a weird relationship since Conda provides its own package manager. Have you tried c[reating a virtual environment](https://github.com/popgenmethods/smcpp#id12) and building in that?
