### ISSUE TITLE
Plot function error

### ISSUE THREAD

**Issue by lwhitacre** [popgenmethods/smcpp#5]
I was able to run data through vcf2smc and estimate. The resulting json file looks correct. However, I cannot plot it. I get the following error:

[lwhitacr@lewis4-r710-login-node223 MDTM.combined.all.filter.SNP.smc.out]$ smc++ plot plot.png model.final.json 
Traceback (most recent call last):
  File "/home/lwhitacr/miniconda3/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.5.1.dev0+ngf20e19d.d20170126', 'console_scripts', 'smc++')()
  File "/home/lwhitacr/miniconda3/lib/python3.5/site-packages/smcpp/frontend/console.py", line 23, in main
    cmds[args.command].main(args)
  File "/home/lwhitacr/miniconda3/lib/python3.5/site-packages/smcpp/commands/plot.py", line 78, in main
    logy=args.logy)
  File "/home/lwhitacr/miniconda3/lib/python3.5/site-packages/smcpp/plotting.py", line 98, in plot_psfs
    xmin = min(xmin, xp[1] * 0.9)
IndexError: index 1 is out of bounds for axis 0 with size 0

If you have any ideas how to proceed, I would appreciate them greatly.

**Comment by terhorst** [comment]
Hmm, haven't encountered this one before. Would you mind uploading your model.final.json? Thanks.

**Comment by lwhitacre** [comment]
Sure. 

[lwhitacr@lewis4-r710-login-node223 MDTM.combined.all.filter.SNP.smc.out]$ cat model.final.json 
{
    "N0": 10000.0,
    "model": {
        "class": "SMCTwoPopulationModel",
        "model1": {
            "class": "SMCModel",
            "knots": [
                0.005,
                0.009102821015130397,
                0.016572270086699935,
                0.030170881682725807,
                0.05492802716530588,
                0.1,
                0.18205642030260796,
                0.3314454017339986,
                0.6034176336545163,
                1.0985605433061172,
                2.0
            ],
            "pid": "Neosho",
            "s": [
                0.005,
                0.0010295427551534819,
                0.0012415344120912863,
                0.0014971769639397503,
                0.0018054585032211221,
                0.002177217847565433,
                0.0026255256198358026,
                0.003166143795910164,
                0.0038180798772808576,
                0.004604255172531213,
                0.005552310683682709,
                0.006695578931432064,
                0.008074255887514904,
                0.009736814217964171,
                0.011741707525240251,
                0.014159425508388696,
                0.0170749722982481,
                0.02059085510306964,
                0.02483068824182573,
                0.029943539278795006,
                0.036109170064422436,
                0.043544356951308705,
                0.05251051239671606,
                0.06332287591820329,
                0.07636159754561711,
                0.09208510345062426,
                0.11104621367365419,
                0.13391157862864134,
                0.16148511775029817,
                0.19473628435928336,
                0.23483415050480505,
                0.283188510167774,
                0.3414994459649616
            ],
            "spline_class": "CubicSpline",
            "y": [
                -4.605170185988091,
                -4.493177166698742,
                -3.973624145232901,
                -3.3014486236141347,
                -2.2126192411488446,
                -1.3599425328158274,
                -0.6440655287225473,
                -0.12400022724953207,
                0.17702183767765406,
                0.5036208930129212,
                0.542783823130174
            ]
        },
        "model2": {
            "class": "SMCModel",
            "knots": [
                0.005,
                0.009102821015130397,
                0.016572270086699935,
                0.030170881682725807,
                0.05492802716530588,
                0.1,
                0.18205642030260796,
                0.3314454017339986,
                0.6034176336545163,
                1.0985605433061172,
                2.0
            ],
            "pid": "Slender",
            "s": [
                0.005,
                0.0010295427551534819,
                0.0012415344120912863,
                0.0014971769639397503,
                0.0018054585032211221,
                0.002177217847565433,
                0.0026255256198358026,
                0.003166143795910164,
                0.0038180798772808576,
                0.004604255172531213,
                0.005552310683682709,
                0.006695578931432064,
                0.008074255887514904,
                0.009736814217964171,
                0.011741707525240251,
                0.014159425508388696,
                0.0170749722982481,
                0.02059085510306964,
                0.02483068824182573,
                0.029943539278795006,
                0.036109170064422436,
                0.043544356951308705,
                0.05251051239671606,
                0.06332287591820329,
                0.07636159754561711,
                0.09208510345062426,
                0.11104621367365419,
                0.13391157862864134,
                0.16148511775029817,
                0.19473628435928336,
                0.23483415050480505,
                0.283188510167774,
                0.3414994459649616
            ],
            "spline_class": "CubicSpline",
            "y": [
                -4.605170185988091,
                -4.605170185988091,
                -4.605170185988091,
                -3.4411159394320205,
                -2.7049406781747054,
                -0.8019817499568547,
                1.2595803237850562,
                -0.00512445749438746,
                0.009311742394317146,
                -0.01186273608563447,
                -0.9135240979378692
            ]
        },
        "split": 0.002606578448510839
    },
    "rho": 0.009996002840327433,
    "theta": 0.015837677947556448

**Comment by lwhitacre** [comment]
Here's the actual file. Had to add ".txt" to upload it...
[model.final.json.txt](https://github.com/popgenmethods/smcpp/files/748415/model.final.json.txt)

**Comment by terhorst** [comment]
Okay, found the bug. I'll have a fix by the end of the day. Thanks for reporting this.

**Comment by lwhitacre** [comment]
Awesome, thank you!

**Comment by terhorst** [comment]
Okay, the latest version now fixes this. To upgrade, type

    $ /path/to/smcpp/bin/conda upgrade -c terhorst smcpp

By the way, the [plot.pdf](https://github.com/popgenmethods/smcpp/files/750914/plot.pdf) that I get using your supplied model looks pretty extreme. The inferred divergence time is extremely recent (more recent than the earliest model time point, which was the cause of the bug) and both populations seem to experience an extreme recent bottleneck. I'm not sure if this is expected for the species you are working with or not. I have previously encountered this behavior when working with data that contained long runs of homozygosity, which were due either to a) actual instances of inbreeding or b) missing centromeres in the VCF which I forgot to mask out. Anyways, let me know if you need further assistance. I've made a few improvements to the optimizer so you might also try re-estimating using the latest version.

**Comment by lwhitacre** [comment]
Thank you for your assistance and speedy fix! I haven't run all the data we have on these guys yet, so the result may change slightly, but they have experienced some recent bottleneck and definitely have some actual instances of inbreeding (deemed a threatened species since 1990). Thanks again.
