### ISSUE TITLE
libgomp: Thread creation failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by dzaccook** [popgenmethods/smcpp#50]
Dear,
I installed the SMC++ (1.9.3), and the GLIBC problem was solved by reinstalling GLIBC, but I got another problem for smc++ estimate, "libgomp: Thread creation failed: Resource temporarily unavailable", the log:
780 smcpp._smcpp INFO SMC++ 1.9.3
1294 smcpp.analysis INFO Loading data...
1971 smcpp.analysis INFO 0.02 Gb of data
1974 smcpp.analysis INFO 1 population
2364 smcpp.analysis INFO theta: 0.000100
2364 smcpp.analysis INFO rho: 0.000100
2364 smcpp.analysis INFO Thinning...
11648 smcpp.analysis INFO Running E-step
13591 smcpp.analysis INFO E-step completed
14006 smcpp.optimize.plugins.progress_printer INFO Starting EM algorithm...
14007 smcpp.optimize.plugins.progress_printer INFO EM iteration 1 of 20...
14007 smcpp.analysis INFO Running E-step
23491 smcpp.analysis INFO E-step completed
23528 smcpp.optimize.plugins.loglikelihood_monitor INFO Loglik: -48431.579379
23534 smcpp.optimize.plugins.parameter_optimizer INFO Updating rho, bounds (0.000002, 0.200000)

libgomp: Thread creation failed: Resource temporarily unavailable

I set the "soft    nproc     unlimited" in file "/etc/security/limits.d/90-nproc.conf", but It is no use. Could you give me some advice?

**Comment by dzaccook** [comment]
I set the "soft nproc 102400", but when "EM iteration 3 of 20..." , I got the same error "libgomp: Thread creation failed: Resource temporarily unavailable", my sample size is 62.

**Comment by terhorst** [comment]
I think this is related to #46. I've fixed the thread creation issue in the devel branch and will merge it soon.
