### ISSUE TITLE
RuntimeError: context has already been set

### ISSUE THREAD

**Issue by PingpingHA** [popgenmethods/smcpp#51]
first , I install  the smc++ 1.10.0 and here comes the error : ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ...).
then, I run "pip install git+https://github.com/popgenmethods/smcpp" . The version seems  change to 1.95??
"Installing collected packages: smcpp
  Found existing installation: smcpp 1.10.0
    Uninstalling smcpp-1.10.0:
      Successfully uninstalled smcpp-1.10.0
  Running setup.py install for smcpp ... done
Successfully installed smcpp-1.9.5.dev44+g205a5e9 "

And now  when I run smc++ ,the error :
   File "../anaconda3/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.9.5.dev44+g205a5e9', 'console_scripts', 'smc++')()
  File "../anaconda3/lib/python3.6/site-packages/smcpp/frontend/console.py", line 22, in main
    mp.set_start_method('forkserver')
  File "../anaconda3/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set

How can I solve it?  
Thank you !

**Comment by aabiddanda** [comment]
@PingpingHA I had the same issue and commented out line 22 in `../anaconda3/lib/python3.6/site-packages/smcpp/frontend/console.py` and it was able to run on v1.10.0 on a RedHat Linux system. In principle a better approach would be to edit the file based on this [forum](https://bugs.python.org/issue18999) I think, but I wanted something that would work quickly

**Comment by PingpingHA** [comment]
@aabiddanda   Thank  you very much for your help !!!

 I edit the 'console.py ':
delete 'mp.set_start_method('forkserver')' 
and insert :
if __name__ == '__main__':
    multiprocessing.set_start_method('forkserver')   

now it works(SMC++ v1.9.5) !!   so happy !!
