### ISSUE TITLE
smc++ estimate error

### ISSUE THREAD

**Issue by Ankitgl** [popgenmethods/smcpp#54]
Hi, I am trying to run the smc++ code. The first step is running fine, however in the second step "estimate" I am getting the following error:

../../anaconda3/bin/smc++ estimate 3.325e-10 out/*.gz -o estimate_out/ 
758 smcpp.analysis INFO Loading data...
33182 smcpp.analysis INFO 0.84 Gb of data
97936 smcpp.analysis INFO 1 population
157271 smcpp.analysis INFO theta: 0.000100
157271 smcpp.analysis INFO rho: 0.000100
171559 smcpp.analysis INFO Running E-step
207175 smcpp.analysis INFO E-step completed
208749 smcpp.optimize.plugins.progress_printer INFO Starting EM algorithm...
208749 smcpp.optimize.plugins.progress_printer INFO EM iteration 1 of 1...
208750 smcpp.analysis INFO Running E-step
244867 smcpp.analysis INFO E-step completed
244874 smcpp.optimize.plugins.loglikelihood_monitor INFO Loglik: -9812623.316696
281194 smcpp.optimize.plugins.progress_printer INFO Current model:

 2.35  2.35  2.35  2.35  2.35  2.35  2.35  2.35  2.35  2.35  2.35  2.35  2.35  2.35  2.34  2.34  2.35
10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.44 10.43 10.43 10.43 10.42 10.42 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.41 10.42 10.42 10.42 10.42 10.42 10.42 10.42 10.42 10.42 10.42 10.42 10.42 10.42 10.42 10.42 10.42 10.42 10.42 10.42 10.42 10.42 10.43 10.43 10.43 10.43 10.43 10.43 10.43 10.43 10.43 10.43 10.44 10.44
Traceback (most recent call last):
  File "../../anaconda3/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.10.0', 'console_scripts', 'smc++')()
  File "/home/nagarjun/anaconda3/lib/python3.6/site-packages/smcpp/frontend/console.py", line 28, in main
    cmds[args.command].main(args)
  File "/home/nagarjun/anaconda3/lib/python3.6/site-packages/smcpp/commands/estimate.py", line 66, in main
    analysis = Analysis(args.data, args)
  File "/home/nagarjun/anaconda3/lib/python3.6/site-packages/smcpp/analysis.py", line 412, in __init__
    self._preinitialize()
  File "/home/nagarjun/anaconda3/lib/python3.6/site-packages/smcpp/analysis.py", line 492, in _preinitialize
    self._t1 = max(self.rescale(50), smcpp.estimation_tools.calculate_t1(self._model, self._max_n, q=.5))
  File "/home/nagarjun/anaconda3/lib/python3.6/site-packages/smcpp/estimation_tools.py", line 202, in calculate_t1
    return scipy.optimize.brentq(f, 0., model.knots[-1])
  File "/home/nagarjun/anaconda3/lib/python3.6/site-packages/scipy/optimize/zeros.py", line 519, in brentq
    r = _zeros._brentq(f,a,b,xtol,rtol,maxiter,args,full_output,disp)
ValueError: f(a) and f(b) must have different signs

----------------------------------------------------------------------------------------------

I am currently working on :
Distributor ID:	Ubuntu
Release:	17.10

Thanks and Regards,

**Comment by terhorst** [comment]
Please upgrade to the latest version. Thanks.

**Comment by Ankitgl** [comment]
Hello Jonathan,

Thanks for your reply. I upgraded to the latest version and the output for the vsf2smc and estimate commands are written below. The "estimate" command is again giving an error.

**$ smc++ vcf2smc PC_variants_filtered.vcf.gz agouti_scaf_13400.smc.gz agouti_scaf_13400 pop1:out.sorted.bam -m FINAL_ASSEMBLY.fasta.out.sorted_bed.gz**
603 smcpp.commands.vcf2smc INFO Population 1:
603 smcpp.commands.vcf2smc INFO Distinguished lineages: out.sorted.bam:0, out.sorted.bam:1
603 smcpp.commands.vcf2smc INFO Undistinguished lineages: 
  0%|                                                                                                                                                         | 0.00/286K [00:00<?, ?bases/s]
1173 smcpp.util   INFO Wrote 96 observations

**$ smc++ estimate 1.33e-09 agouti_scaf_13400.smc.gz -o agouti_scaf_13400.estimate**
602 smcpp.analysis INFO theta: 0.000100
602 smcpp.analysis INFO rho: 0.000100
602 smcpp.data_filter INFO Loading data...
680 smcpp.data_filter INFO 0.00 Gb of data
691 smcpp.data_filter INFO 1 population
Traceback (most recent call last):
  File "/home/ankitg/smcpp/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.11.1.dev0', 'console_scripts', 'smc++')()
  File "/home/ankitg/smcpp/lib/python3.6/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/home/ankitg/smcpp/lib/python3.6/site-packages/smcpp/commands/estimate.py", line 71, in main
    analysis = Analysis(args.data, args)
  File "/home/ankitg/smcpp/lib/python3.6/site-packages/smcpp/analysis.py", line 208, in __init__
    q = smcpp.beta_de.quantile(mc / w, 1. / w, np.geomspace(1e-2, .99, args.hs * args.knots))
  File "/home/ankitg/smcpp/lib/python3.6/site-packages/smcpp/beta_de.py", line 28, in quantile
    y /= y[-1]
FloatingPointError: invalid value encountered in true_divide

-------------------------------------------------------------------------------------------------------------------

Also, "estimate" command is giving "ERROR All contigs are <.01cM (estimated)" error when using contigs less than 100,000 bp. Is there any way of running smcpp on smaller contigs (say around 10 kb) as well.


Thanks and Regards,
Ankit

**Comment by terhorst** [comment]
From the log you're trying to run it on < 50Kb worth of data. This method is designed to work with much larger data sets (genome-length data from 100s of samples). Even if Ne were *constant* you would have a hard time estimating it accurately using so little data.

**Comment by terhorst** [comment]
Sorry, I think I understand what the the problem is now. It appears almost all of your contigs have been dropped because they are short. You can confirm this using the ``-v`` option. You can lowering the ``--length-cutoff`` option to keep more contigs. I'd add that, if all of your contigs are this short there is not going to be any gain from using a method like SMC++ which takes advantage of linkage information. You would be better off using a frequency-spectrum method like fastsimcoal2.

**Comment by Ankitgl** [comment]
Thank you for your comments and suggestions.

Regards
