### ISSUE TITLE
Query regarding the example file

### ISSUE THREAD

**Issue by cooken1** [popgenmethods/smcpp#55]
Hello,

I have been using SMC++ to examine the available example file (https://github.com/popgenmethods/smcpp/tree/master/example). The following commands produced the image below:

```
for i in {0..4};
    do /path/to/smc++ vcf2smc -d msp_$i msp_$i example.vcf.gz out.$i.txt 1 nov14:msp_0,msp_1,msp_2,msp_3,msp_4;
done
/path/to/smc++ estimate 1e-8 out.*.txt -o out.estimate
 /path/to/smc++ plot 0_to_4.png model.final.json
```

![image](https://user-images.githubusercontent.com/31613997/32843298-562d3fe0-ca17-11e7-9ce7-790199286249.png)

I was just wondering what the nature of this data was, and if this graph is accurately informative about the population history of these "msp" individuals?

**Comment by terhorst** [comment]
It was generated by msprime. It's 1Mb long and is there for illustration
and testing purposes only.

**Comment by cooken1** [comment]
Was this example designed to simulate any model of population expansion and decline? And if so, does the above graph resemble that simulation?

**Comment by terhorst** [comment]
No.

**Comment by cooken1** [comment]
Ok, thanks for the speedy response.
