### ISSUE TITLE
"--mask" of vcf2smc

### ISSUE THREAD

**Issue by dzaccook** [popgenmethods/smcpp#56]
Hi,
My data was stored in VCF file, and I EXCLUDED the SNPs with "MAF<0.05, Max-missing >0.3", and other missing data was signed to ./., should I set the "--mask" when I start using vcf2smc?
Best wishes,

**Comment by terhorst** [comment]
As long as you correctly coded all missing data as './.' (including things
like centromeres, which are often omitted) then this should be fine. Note
that filtering based on MAF will introduce biases in the SFS which are not
currently corrected for in this program.
