### ISSUE TITLE
undistinguished individuals and bottlenecks

### ISSUE THREAD

**Issue by mattingsdal** [popgenmethods/smcpp#57]
I am working on an organism and we identify three distinct populations, shaped by none, one and two bottlenecks. As I understand I should calculate a combined log-likelihood between 2-3-4 individuals. But, the inferred results depend somewhat on what I define as undistinguished individuals, and I need some advice. 

What do you think is more appropriate to use as undistinguished individuals: all samples, population of origin (very heterozygous) or actual/derieved population (very homozygous)?

**Comment by terhorst** [comment]
I don't understand the distinction between population of origin and
actual/derived population. In general though, it does not make sense to
combine individuals from multiple distinct populations when forming the
composite likelihood. The model assumes that all sampled individuals are
from a single panmictic population. We offer limited support for
two-population isolation-without-migration models using the split command.
