### ISSUE TITLE
Different results between MSMC2 and SMCPP

### ISSUE THREAD

**Issue by biozzq** [popgenmethods/smcpp#6]
Hi @terhorst 

I have run `MSMC2` and `SMCPP` using same individuals (four individuals for one population) to estimate the effective population size, but the results are somewhat different (the generation time set in MSMC2 is 5 years). I note that the good agreement before 10,000 years ago for `MSMC2` but in contrast for `SMCPP` (I do not know why, I have attached my commands following).
The domestication of these studied animals are occurred about 10,000 years ago, so I think they should have a low dispersion refer to their effective population size before domestication.  As you suggested in your paper, `MSMC2` has a low resolution in the recent past for the effect of phasing error (may be more serious in animals which do not have reference panels).  But for their different results in the distant past (before 10,000 years), I am afraid that I have made some mistakes on running `SMCPP`. You said that you can get reasonable results using panels of 100-200 individuals per population, but in animals, the big panels may be impossible.  In my condition, some populations have more than 20 individuals, and some have no more than 10 individuals. So I want to know can I compare the results from different sample size among different population. If I want to inferred divergence time about 5,000 years ago, how many individuals do you think I should include in each population. 

What is more, I can not find the parameter for mutation rate when running plot.  

Command,
for each chromosome
`smc++ vcf2smc --mask $chr.mask.bed.gz auto.vcf.gz $chr.smc.gz $chr $poplabel:$popname`
then estimate Ne
`smc++ estimate -o $poplabel 1.smc.gz 2.smc.gz 3.smc.gz 4.smc.gz 5.smc.gz 6.smc.gz 7.smc.gz 8.smc.gz 9.smc.gz 10.smc.gz 11.smc.gz 12.smc.gz 13.smc.gz 14.smc.gz 15.smc.gz 16.smc.gz 17.smc.gz 18.smc.gz 19.smc.gz 20.smc.gz 21.smc.gz 22.smc.gz 23.smc.gz 24.smc.gz 25.smc.gz 26.smc.gz 27.smc.gz 28.smc.gz 29.smc.gz`
![sas](https://cloud.githubusercontent.com/assets/15704257/22737909/325204ce-ee40-11e6-8c0d-9aa156896d8f.png)
![cns](https://cloud.githubusercontent.com/assets/15704257/22737912/34ab9a28-ee40-11e6-90d3-e94f83412f3d.png)
![tib](https://cloud.githubusercontent.com/assets/15704257/22737916/360f1bba-ee40-11e6-9ca5-1833d10a94a4.png)
![cnn](https://cloud.githubusercontent.com/assets/15704257/22737918/37983250-ee40-11e6-9eef-74c10620f9be.png)
![msmc2](https://cloud.githubusercontent.com/assets/15704257/22741052/d57b7f5c-ee4c-11e6-91ab-661f73ddc582.png)

Hope for your help
Best
Zhuqing

**Comment by terhorst** [comment]
The commands you are running look okay, but clearly the optimizer is failing to find a good estimate. I would suggest increasing the value of some of the regularization parameters in SMC++. I have added some [discussion in the README](https://github.com/popgenmethods/smcpp#tips-for-using-smc) about how to do this. Also, try updating to the latest version of SMC++, as I have fixed a few issues pertaining the the optimizer in recent versions. (If using the conda version, you can do this easily by 

    /path/to/smcpp/bin/conda upgrade -c terhorst smcpp

Thanks.

**Comment by biozzq** [comment]
Hi @terhorst 

Thanks, I will try the latest version.  

If I want to analyse population separation, but different subpopulations have different sample size, such as 8 individuals from population 0 and 20 individuals from population 1,  can I use this unbalance sample size to estimate population separation?

How can I set mutation rate when running `smcpp`, maybe I have missed some information because I just noticed `--theta` , so I do not know whether the `Ne` in `smcpp` plot is same with `Ne` in `MSMC2` plot.  I suspect this because their difference from above plots.

Best
Zhuqing

**Comment by terhorst** [comment]
Using different numbers of individuals from different subpopulations is ok for running ``split``. 

The option ``--theta`` sets the scaled mutation rate (i.e. ``2 N0 mu``). By default the scaling is with respect to ``N0=10000`` but you can change this using ``--N0``. To convert to units of ``Ne``, ``plot`` multiplies by whatever ``N0`` you specified in ``estimate``. So assuming you used the same scaled mutation rate for both MSMC and SMC++ they should be in the same units. Note that in our paper we encountered issues with the accuracy of MSMC in the recent past due to phasing error.

**Comment by hugang123** [comment]
@biozzq Hi,i am interested in your smc++ plot grap.I found your graph was smoothing,could you share the coding with me,thans.
