### ISSUE TITLE
different results using "-c"

### ISSUE THREAD

**Issue by dzaccook** [popgenmethods/smcpp#60]
Hi,
I mask the region with "-c", however, I got a different result when I set "-c 10kb" and "-c 100kb", how should I determine the result?
![1513660668699](https://user-images.githubusercontent.com/23490134/34141868-0baa9586-e4bf-11e7-9779-4c8ce0876034.jpg)
Best wishes

**Comment by terhorst** [comment]
``-c`` is a bit of a hack used to work around the fact that some variant callers don't bother to emit missing data calls for unmappable/uncallable regions. There's no real "correct setting". I recommend using ``--mask`` to correctly mark those regions as such instead of relying on ``-c``.
