### ISSUE TITLE
context has already been set

### ISSUE THREAD

**Issue by huangl07** [popgenmethods/smcpp#61]
Traceback (most recent call last):
  File "/home/huangl/publib/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.9.5.dev45+gb4a1220', 'console_scripts', 'smc++')()
  File "/home/huangl/publib/lib/python3.6/site-packages/smcpp-1.9.5.dev45+gb4a1220-py3.6-linux-x86_64.egg/smcpp/frontend/console.py", line 22, in main
    mp.set_start_method('forkserver')
  File "/home/huangl/publib/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set

**Comment by yorkklause** [comment]
It seems I got the same problem. Anyone could help me fix it?

**Comment by yuntwang** [comment]
I got the same problem. Did you solve it @yorkklause  @yorkklause

**Comment by terhorst** [comment]
What version are you running? This should have been fixed in the last two
versions (1.11.0dev and 1.12.0).

**Comment by yorkklause** [comment]
I just using this command line to install the smcpp
pip install git+https://github.com/popgenmethods/smcpp
I guess the version should be the latest version.
My Python version is 3.6.4(latest)
gcc is 4.9.4(support the c++11)
gmp is 6.1.2(support the gmpxx)
mpfr is 3.1.6
gsl is 2.4
Maybe you can help me install a previous version of smcpp.
Thanks~

**Comment by yorkklause** [comment]
The problem has not fixed yet. @yuntwang

**Comment by terhorst** [comment]
Try pip install git+https://github.com/popgenmethods/smcpp@v1.12.0

**Comment by yorkklause** [comment]
Thanks for your reply, the problem has been fixed.
