### ISSUE TITLE
Expected a diploid genotype at position 347 for individual F_1 but found

### ISSUE THREAD

**Issue by huangl07** [popgenmethods/smcpp#63]
hi,my data is a stacks output for unref vcf files.

it turn out error when vcf2smc 

```
$smc++ vcf2smc -l 483292718 --ignore-missing pop.recode.vcf.gz test un F:F_1 
3680 smcpp.commands.vcf2smc WARNING Neither missing cutoff (-c) or mask (-m) has been specified. This means that stretches of the chromosome that do not have any VCF entries (for example, centromeres) will be interpreted as homozygous recessive.
3681 smcpp.commands.vcf2smc INFO Population 1:
3681 smcpp.commands.vcf2smc INFO Distinguished lineages: F_1:0, F_1:1
3681 smcpp.commands.vcf2smc INFO Undistinguished lineages: 
[W::bcf_hdr_check_sanity] GL should be declared as Number=G
  0%|                                                                                                                                  | 347/483M [00:00<31:25, 256kbases/s]
3725 smcpp.util   INFO Wrote 0 observations
Traceback (most recent call last):
  File "/mnt/ilustre/users/dna/.env//bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.12.0', 'console_scripts', 'smc++')()
  File "/mnt/ilustre/users/dna/.env/lib/python3.6/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/mnt/ilustre/users/dna/.env/lib/python3.6/site-packages/smcpp/commands/vcf2smc.py", line 254, in main
    abnb = rec2gt(rec)
  File "/mnt/ilustre/users/dna/.env/lib/python3.6/site-packages/smcpp/commands/vcf2smc.py", line 164, in rec2gt
    "for individual {} but found:\n{}".format(rec.pos, d, rec))
RuntimeError: Expected a diploid genotype at position 347 for individual F_1 but found:
un	347	3_83	T	A	.	PASS	.	GT:DP:AD	0/1:4:2,2	./.:0:.,.	0/0:10:10,0	1/1:4:0,4	./.:0:.,.	./.:0:.,.  0/0:8:8,0	0/0:17:17,0	0/0:10:10,0	0/0:14:14,0	0/0:5:5,0	0/0:7:7,0	./.:0:.,.	0/0:12:12,0	0/0:7:7,0	0/0:4:4,0	0/1:18:8,100/0:15:15,0	0/0:13:13,0	0/0:10:10,0	0/0:14:14,0	0/0:42:42,0	./.:0:.,.	0/0:4:4,0	0/0:11:11,0	0/0:7:7,0	0/0:16:16,0	0/0:21:21,00/0:6:6,0	0/0:9:9,0	0/0:30:30,0	./.:0:.,.	0/0:16:16,0	0/0:5:5,0	./.:0:.,.	0/1:21:9,12	0/0:4:4,0	0/0:4:4,0	0/0:11:11,00/0:8:8,0	0/0:10:10,0	0/0:6:6,0	0/0:21:21,0	0/0:12:12,0	0/0:4:4,0	0/0:6:6,0	0/0:11:11,0	0/0:7:7,0	0/0:7:7,0	0/0:20:20,00/1:16:11,5	./.:0:.,.	./.:0:.,.	./.:0:.,.	0/0:8:8,0	./.:0:.,.	./.:0:.,.	0/0:20:20,0	0/0:19:19,0	0/0:10:10,0

```
is there someting wrong

**Comment by terhorst** [comment]
This bug is fixed in the most recent version.

**Comment by arbel-harpak** [comment]
Hey, still running into this error with current version. 
Thanks in advance.

3865 smcpp.util   INFO Wrote 42 observations
Traceback (most recent call last):
  File "/scg/apps/software/smcpp/1.15.2/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.15.2', 'console_scripts', 'smc++')()
  File "/scg/apps/software/smcpp/1.15.2/lib/python3.6/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/scg/apps/software/smcpp/1.15.2/lib/python3.6/site-packages/smcpp/commands/vcf2smc.py", line 255, in main
    abnb = rec2gt(rec)
  File "/scg/apps/software/smcpp/1.15.2/lib/python3.6/site-packages/smcpp/commands/vcf2smc.py", line 165, in rec2gt
    list(rec.samples[d].alleles)))
RuntimeError: Expected a diploid genotype at position 1912 for individual RH2-06 but found:
['C']

**Comment by terhorst** [comment]
Can you post a snippet of the vcf for that sample at that site?

**Comment by arbel-harpak** [comment]
Yes. Here's the line its having problems with; presumably due to the missing data filled in with REF?

chr1	1912	.	C	T	1684.31	PASS	AC=5;AF=0.278;AN=18;BaseQRankSum=1.45;ClippingRankSum=0;DP=189;ExcessHet=1.5127;FS=0.778;MLEAC=5;MLEAF=0.278;MQ=47.91;MQRankSum=0.553;QD=17.19;ReadPosRankSum=0.326;SF=1;SOR=0.542	GT:GQ:DP:PL:AD	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0:.:.:.:.	0/0:18:6:0,18,215:6,0	0/1:99:54:953,0,917:27,27	0/1:99:22:350,0,379:12,10	0/0:51:17:0,51,673:17,0	0/0:54:18:0,54,702:18,0	0/0:99:37:0,102,1389:37,0	1/1:24:8:324,24,0:0,8	0/0:33:11:0,33,436:11,0	0/1:99:14:112,0,345:10,4

**Comment by terhorst** [comment]
`vcf2smc` assumes that the input matches the [specification](https://samtools.github.io/hts-specs/VCFv4.2.pdf). In this case, the coding of the first ~20 missing samples (`0:.:.:.:.`) is incorrect. If you recode the file to comply with the spec (see section 1.4.2 of the linked document), it should work.
