### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by huangl07** [popgenmethods/smcpp#64]
when I was smc++ estimate
it turns out 
/mnt/ilustre/users/dna/.env/lib/python3.6/multiprocessing/semaphore_tracker.py:129: UserWarning: semaphore_tracker: There appear to be 4 leaked semaphores to clean up at shutdown

**Comment by terhorst** [comment]
Can you please copy and paste the logging output and exact error message that you received?

**Comment by huangl07** [comment]
sorry about that， I will paste it tomorrow

by the way，I have used pip install a AMD CPUs cluster，but it run error in an Intel CPU node，is there any help for you

**Comment by terhorst** [comment]
Oh that probably explains it. You need to use something like `--mtune=generic` if you're going to do that.

**Comment by huangl07** [comment]
it is for rebuild？ or when running smcpp？ thanks for your replay

**Comment by huangl07** [comment]
![image](https://user-images.githubusercontent.com/32302403/35021319-4b7b6e7a-fb6b-11e7-8333-af7ef8ff9e2d.png)

sorry about that,I have no idea -mtune=generic，Can you explain more detail？

**Comment by huangl07** [comment]
？ hi terhosrst？

**Comment by terhorst** [comment]
The reason you are getting `Illegal instruction` is that the compiler is using Intel-specific instructions which don't exist on the AMD architecture (or vice versa). `--mtune=generic` prevents this from happening. You can enable it by modifying the Makefile or setting `CFLAGS` appropriately.

**Comment by huangl07** [comment]
I‘m very sorry about it doen't work
