### ISSUE TITLE
About  the per-generation mutation rate

### ISSUE THREAD

**Issue by hugang123** [popgenmethods/smcpp#65]
Hi,@terhorst. I was confused with the u parameter when i used the  command "smc++ estimate  --t1 1e+2 --tK 1e+7  -o ./   2.2e-9  ../*smc.gz" .As you said ,the mutation rate means the per-generation mutation rate(per base per generation), but usually we just had the evolutionary rate (per base per year).So should i use the evolutionary rate multiply the 20 years as the input mutation rate if the species generation is 20 years?

**Comment by terhorst** [comment]
Yes.
