### ISSUE TITLE
sequence depth?

### ISSUE THREAD

**Issue by yuntwang** [popgenmethods/smcpp#67]
Great software!
I have a little confused about the sample sequence depth,
maybe，what is the  restrictions,10x,20x……
and sequence method, Resequence or  RAD and so on.
Hope to get your reply.
Thanks.

**Comment by terhorst** [comment]
SMC++ operates at the level of biallelic genotypes; it knows nothing about coverage levels, sequencing strategies and so forth. You should have enough coverage to obtain relatively error-free genotypes. So far I have only used it to analyze WGS data (and array data in a separate forthcoming project). I don't know much about RADseq but my impression is that the genotypes you would obtain would be spread pretty far apart, i.e. they would be in linkage equilibrium. In that case there would be no gain to using SMC++ over a frequency-spectrum based method like momi, dadi, or fastSimCoal or fastNeutrino.
