### ISSUE TITLE
Choice of distinguished pairs

### ISSUE THREAD

**Issue by grafau** [popgenmethods/smcpp#68]
Hello!

While using smc++ for my inbreeding species, I stumbled across an interesting problem. The selection of distinguished pairs usually falls for two "chromosomes" of a single individual. Unfortunately, this approach won't work for inbreeding species, in which cases we deficit of heterozygous sites. 

Instead, it would be logical to pick two different individuals. I did some testing and noticed that the selection of two distinguished pairs changes the outcome of analysis (see attached images). Hence, I have a question if there is any logical guideline for picking up a pair. Should the two individuals represent "most" or "least" diversity in sampled population?

I would very much welcome any guidance in this matter.

Cheers,
Rafal
<img width="562" alt="screen shot 2018-01-31 at 1 57 13 pm" src="https://user-images.githubusercontent.com/35376323/35644826-0f3d1110-0698-11e8-9486-0b4fcba8e700.png">
<img width="560" alt="screen shot 2018-01-31 at 1 55 49 pm" src="https://user-images.githubusercontent.com/35376323/35644827-0f653492-0698-11e8-8e83-d873ab630399.png">

**Comment by terhorst** [comment]
It is unfortunately true that the likelihood surface can change from pair to pair, and I currently don't know of any principled way to choose between them. Usually we would combine information from all of the distinguished pairs into a composite likelihood and use that for estimation. If you have not already, you should also try upgrading to the latest release. The default settings are designed to exhibit less variance in terms of the model fit.

**Comment by grafau** [comment]
Thanks for being honest about it! I am running latest 1.12.1. vcf2smc for all pairwise options doesn't scale well with number of individuals in population, so I will try some sampling strategy. Sounds like pure random sampling could do the job. Cheers!

**Comment by terhorst** [comment]
Sorry, yes, that's correct, running all n(n-1)/2 pairs is not feasible, nor do I think it would be good from a statistical point of view. Usually I randomly sample about O(n) pairs and use that for estimation.
