### ISSUE TITLE
Incoorporating aDNA

### ISSUE THREAD

**Issue by harlydurbin** [popgenmethods/smcpp#7]
I have a question about running estimate and plot with ancient samples alongside extant populations... In the paper, how did you go about  plotting your ancient individual without extending the population estimate to present day? We have a 14kya sample we're trying to incorporate and would like to use to run 'split' in order to look at speciation/divergence times. Besides altering the mutation rate, are there any other considerations we should take into account?

**Comment by terhorst** [comment]
There is an option ``--offsets`` to ``plot`` which you can use to shift population(s) back in time, like for aDNA analysis. Unfortunately it is not yet able to handle a two-population model where one of the populations is ancient and the other is not. Until I have time to add that feature, you can use the ``-c`` option of ``plot`` to generate a CSV containing the raw data points of the plot, and then shift your aDNA lineage back in time manually. 

When analyzing the aDNA sample in our paper, it helped to [regularize](https://github.com/popgenmethods/smcpp#tips-for-using-smc) a bit more strongly than for the modern populations. Also, if (as is usually the case) you have only a single sample from your aDNA population, I think the estimates from ``split`` could be noisier compared to analyzing hundreds of samples from each subpopulation. (We're currently working on an extension to SMC++ that is more suited to analyzing pairs of populations by allowing for migration between them, but it's a ways off.) Thanks.
