### ISSUE TITLE
`ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory`

### ISSUE THREAD

**Issue by molecules** [popgenmethods/smcpp#70]
After resolving #69 locally, I tried running `smc++ --help` and got the following error:
`ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory`

I found the almost identically named file `/usr/lib64/libbz2.so.1`, but there isn't a `lib64` directory for `smcpp`, so I wasn't sure if that is what I really need.

Please advise.

Thanks so much for all of your work on `smc++`!

**Comment by terhorst** [comment]
I put up a new version of the installer which should fix this as well as the other issue you submitted. Thanks for reporting the bugs.

**Comment by molecules** [comment]
Thanks!
