### ISSUE TITLE
Stopping before likelihood score reaches tolerance?

### ISSUE THREAD

**Issue by melop** [popgenmethods/smcpp#72]
Hi, I notice that in the log file that the iteration seems to stop before the tolerance is reached:

4425647 smcpp.optimize.plugins.loglikelihood_monitor INFO New loglik: -8572884.817009	(old: -8573699.931825 [0.009507%])
4425647 smcpp.optimize.plugins.loglikelihood_monitor INFO Log-likelihood improvement < tol=0.0001; terminating  

The log likelihood improvement between the current and the previous iterations is 815, much higher than the tolerance of 0.0001, but somehow the program decides to stop.

SMC++ version is v1.9.3

(I have trouble installing the latest version)

Ray

**Comment by terhorst** [comment]
It's relative tolerance. .0001 = .01% which is larger than the improvement
shown in the previous line.

**Comment by melop** [comment]
Hi Jonathan, thanks!

I set ftol to a lower value and now it works. 

It seems that though if I set xtol to 0.00001, the program still honors the relative tolerance of 0.01% instead of using the xtol value set by the user.

Ray
