### ISSUE TITLE
split command takes a lot of RAM

### ISSUE THREAD

**Issue by melop** [popgenmethods/smcpp#73]
Hi Jonathan,

I am running into trouble when trying out the split command. It is taking a lot of RAM on a dataset that contains a variable level of missing data (i.e. the number of total sampled chromosomes differ from site to site).

The estimate command ran successfully on the same input files.

I am using a node with 250Gb of RAM. As you can see, the split command eventually gets killed after taking up too much RAM:
>top
> 43777 RCui      20   0 99.997g 0.093t  17796 R 475.7 38.0 135:01.25 smc++         

                                                                                                                                 
These are the last few lines from the log file before the RAM consumption exploded:

> 13602 smcpp.analysis INFO 2 populations
> 46714 smcpp.analysis DEBUG Watterson estimator: 0.006112
> 101713 smcpp.analysis DEBUG Creating inference manager...
> 101713 smcpp.analysis DEBUG Creating inference manager for (('RACWET', 'RACDRY'), (112, 118), (2, 0))

This doesn't happen if I use a dataset with imputed genotypes (i.e. all individuals are non-missing).

Is this an expected behavior?

Best Regards,
Ray

**Comment by terhorst** [comment]
I believe you said you are running on old version? It's fixed in recent
versions.

**Comment by melop** [comment]
Thanks Jonathan!

Do I have to rerun the estimate command if these were run with version 1.9.3? Any changes to that command in the latest update?

Best,
Ray

**Comment by melop** [comment]
Ok, now I can see that I have to rerun estimate.

Do I also need to rerun vcf2smc? Did this command change its behavior from 1.9.3?

Ray

**Comment by melop** [comment]
I finally managed to upgrade to the latest version. Unfortunately the split command still seems to take up a lot of RAM although it seems like the RAM usage increases slower than before.. 

As of now it is taking up 234Gb of RAM.

13195 RCui      20   0  0.234t 0.229t   1148 R  53.0 93.0  97:40.88 smc++                                                                                                                                           

Do I need to rerun the vcf2smc command using the latest version? Currently I'm using the smc input generated by vcf2smc 1.9.3.

Thanks!
Ray

**Comment by terhorst** [comment]
It should not be necessary to re-run vcf2smc, no. How much data do you have?

**Comment by melop** [comment]
The reference genome is around 1.1Gb, we have 60 individuals with a mean coverage of 2.3X. The distinguished individual has 7X coverage. Variants were called with samtools for each of the two populations. 
I tried running split with chromosome 1 only, and it finished successfully, consuming 100Gb of RAM.
 
Ray

**Comment by terhorst** [comment]
Sorry for the delay. I have tested split in various ways on my system and I do not see anything like this level of memory consumption. With two populations totaling >300 samples on human chromosome 1 it consumes 800Mb of RAM on my machine. If you have a really high level of missing data that could be the culprit. Essentially SMC++ needs to compute and store one matrix for every unique span of missing observations in your data set. However, even in that case it's hard to see from my back of the envelope calculations how you get to 100Gb from the data as you described it.

**Comment by melop** [comment]
I guess that the human samples were quite complete, with almost no missing genotypes? 
I masked regions with coverage <1/2x and >2x. Not sure if that makes any difference. 
It is indeed strange, hmm...

**Comment by melop** [comment]
I can confirm that this still happens in the latest version on our dataset. We have now increased the coverage of the distinguished individual to >20x. Currently I'm only able to use chromosome 1 for the split analysis.

**Comment by melop** [comment]
Dear Jonathan,

    After using high coverage data on the distinguished individual, smc++ cannot run on even just chromosome 1 in a system with 500Gb of RAM.

    I can transfer you the input files if that helps with making improvements.

Thanks!
Ray
Ray

**Comment by terhorst** [comment]
How much variability is there in the sample size (last column of the .smc file)? I think it's as you said above, if there is a wide range in the # of missing samples across sites, it's going to consume a lot of memory. I don't think it's a bug in SMC++. You could try downsampling to make the sample size constant, or imputation.

**Comment by terhorst** [comment]
How much variability is there in the sample size (last column of the .smc file)?

**Comment by melop** [comment]
Yes - after imputing the genotypes it now runs fine with all chromosomes. I think it's due to variation in the missing data.
