### ISSUE TITLE
Dadi results is not consistent with SMCPP

### ISSUE THREAD

**Issue by biozzq** [popgenmethods/smcpp#76]
Dear @terhorst 

In order to investigate the gene flow, I also ran the dadi to infer the demographic.  The split time seems ok (consistent with smcpp) just for the simple isolation model. But when I add migration (IM model or other model which involved migration), the model will give me a very long divergence time (e.g, 10,000 years for SMCPP but 100,000 for dadi). I also try fastsimcoal2 which also give me a long time. Have you encountered a similar situation? Hope you can give me some suggestions. Thank you.

Best
Zhuqing

**Comment by yss1** [comment]
I strongly recommend reading our paper before using the software.  For estimating divergence times, our current implementation assumes a clean-split model (i.e., no gene flow), as described in the paper. 

Yun S. Song

**Comment by terhorst** [comment]
Gene flow would make the results wrong. If you are certain that there is
gene flow then you shouldn't use the split estimation procedure in SMC++.
We just released another method than is designed to analyze gene flow:

https://www.biorxiv.org/content/early/2018/03/23/287268
