### ISSUE TITLE
Variant quality filter & sequencing error?

### ISSUE THREAD

**Issue by melop** [popgenmethods/smcpp#77]
I am wondering what the lowest variant quality in the vcf file is accepted by the vcf2smc command?
Or does it ignore the variant quality field in the vcf?
Very low variant quality may suggest sequencing error. If these are not filtered out, it's likely for smc++ to infer a recent population expansion?

Thanks!
Ray

**Comment by terhorst** [comment]
Correct: [variant quality scores are ignored by vcf2smc](https://github.com/popgenmethods/smcpp#caveats). Spurious variants can potentially distort the recent size history. You should filter them out as you see fit before running vcf2smc.

**Comment by melop** [comment]
Thanks. Should these sites be given in the mask bed file or should they be simply deleted from the VCF (treated as invariant sites)?

**Comment by terhorst** [comment]
The more conservative option would be to mask them out as missing. Unless there are a lot I wouldn't expect it to make a big difference though.

**Comment by melop** [comment]
Thanks!

One more thing to clarify. If all individuals for a population are marked as missing "./." for a site, what would vcf2smc do? Does it treat them all as homozygous reference, masked, or something else?

**Comment by terhorst** [comment]
It would code them all as missing in the output file. Then, during inference, this site would contribute nothing to the likelihood.

**Comment by melop** [comment]
Thanks for the clarification.
Ray
