### ISSUE TITLE
Unit of the fitted rho

### ISSUE THREAD

**Issue by melop** [popgenmethods/smcpp#78]
Dear Jonathan, 

In the JSON output, what is the unit of rho? Is it in the unit of 2N0/bp ? 

For example, if in this json output  rho = 0.00168, N0 = 19011.4, then r = 0.00168 / (2*19011.4) = 4.418e-8?

I also notice that "theta" is always 0.0001, what does this mean?

Thank you!

Ray

**Comment by terhorst** [comment]
Sorry for the delay, I missed this issue. Your math is correct. theta is the population-scaled mutation rate. N0 is chosen such that 2 * N0 * mu = theta.
