### ISSUE TITLE
masking problem?

### ISSUE THREAD

**Issue by hudja** [popgenmethods/smcpp#79]
Hi! I am have a set of full vcf files, which include both variant and invariant positions. The only positions missing in these files are those for which reference genotype is unknown in human reference genome. These files are huge and also include a lot of low quality genotypes. To save some time and space I removed all Low Qual positions using 'bcftools filter -e'F_MISSING>0.01' to exclude all SNPs with more than 1% of missing data. Next, I created a bed mask file which includes all positions missing from my processed vcfs. For example, for this data:
20	1	.	T	C	.	PASS	.	GT
20	2	.	T	C	.	PASS	.	GT
20	4	.	T	C	.	PASS	.	GT
my mask will look like:
20	3	4

Next, I used processed vcf and --mask flag with the latest smc++. My vcf2smc conversion completes *successfully*, but
when I run estimate I am getting the following error:
Traceback (most recent call last):
  File "/home/hudja/anaconda3/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.12.1', 'console_scripts', 'smc++')()
  File "/home/hudja/anaconda3/lib/python3.6/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/home/hudja/anaconda3/lib/python3.6/site-packages/smcpp/commands/estimate.py", line 71, in main
    analysis = Analysis(args.data, args)
  File "/home/hudja/anaconda3/lib/python3.6/site-packages/smcpp/analysis.py", line 208, in __init__
    q = smcpp.beta_de.quantile(mc / w, 1. / w, np.geomspace(1e-2, .99, args.hs * args.knots))
  File "/home/hudja/anaconda3/lib/python3.6/site-packages/smcpp/beta_de.py", line 28, in quantile
    y /= y[-1]
FloatingPointError: invalid value encountered in true_divide

When I try run vcf2smc and estimate without masking, it works fine. The mask seems fully valid, and vcf2smc conversion finishes normally with it. The number of observations written with mask also seems normal.
Here are the examples of masked and unmasked smc files.
https://www.dropbox.com/sh/yl7qxgz06ug2qay/AADPnd7SY875KG14SJHHUtMCa?dl=0

Commands I was using are:

smc++ vcf2smc --mask tst.mask.gz tst.vcf.gz tst_with_mask.smc.gz 21 TST:LP6005441-DNA_F08,LP6005442-DNA_D01,LP6005441-DNA_F04,LP6005441-DNA_E08,LP6005443-DNA_C02,LP6005441-DNA_D06,LP6005441-DNA_C06,LP6005443-DNA_C06,LP6005592-DNA_C02,LP6005519-DNA_B06

smc++ vcf2smc tst.vcf.gz tst_without_mask.smc.gz 21 TST:LP6005441-DNA_F08,LP6005442-DNA_D01,LP6005441-DNA_F04,LP6005441-DNA_E08,LP6005443-DNA_C02,LP6005441-DNA_D06,LP6005441-DNA_C06,LP6005443-DNA_C06,LP6005592-DNA_C02,LP6005519-DNA_B06

smc++ estimate -o tmp/ --cores 32 1.45e-8 tst_with_mask.smc.gz

smc++ estimate -o tmp/ --cores 32 1.45e-8 tst_without_mask.smc.gz

Thank you in advance!

**Comment by terhorst** [comment]
Thanks for the helpful bug report. The issue is that when you apply the mask, >90% of the sites become missing. This is ok for inference, but it causes problems for the heuristic we use to try and auto-calculate the correct time points. The fix I have added at least causes it to print out an informative error message in this case.

**Comment by selasphoruskershaw** [comment]
> Hi! I am have a set of full vcf files, which include both variant and invariant positions. The only positions missing in these files are those for which reference genotype is unknown in human reference genome. These files are huge and also include a lot of low quality genotypes. To save some time and space I removed all Low Qual positions using 'bcftools filter -e'F_MISSING>0.01' to exclude all SNPs with more than 1% of missing data. Next, I created a bed mask file which includes all positions missing from my processed vcfs. For example, for this data:
> 20 1 . T C . PASS . GT
> 20 2 . T C . PASS . GT
> 20 4 . T C . PASS . GT
> my mask will look like:
> 20 3 4
> 
> Next, I used processed vcf and --mask flag with the latest smc++. My vcf2smc conversion completes _successfully_, but
> when I run estimate I am getting the following error:
> Traceback (most recent call last):
> File "/home/hudja/anaconda3/bin/smc++", line 11, in
> load_entry_point('smcpp==1.12.1', 'console_scripts', 'smc++')()
> File "/home/hudja/anaconda3/lib/python3.6/site-packages/smcpp/frontend/console.py", line 26, in main
> cmds[args.command].main(args)
> File "/home/hudja/anaconda3/lib/python3.6/site-packages/smcpp/commands/estimate.py", line 71, in main
> analysis = Analysis(args.data, args)
> File "/home/hudja/anaconda3/lib/python3.6/site-packages/smcpp/analysis.py", line 208, in **init**
> q = smcpp.beta_de.quantile(mc / w, 1. / w, np.geomspace(1e-2, .99, args.hs * args.knots))
> File "/home/hudja/anaconda3/lib/python3.6/site-packages/smcpp/beta_de.py", line 28, in quantile
> y /= y[-1]
> FloatingPointError: invalid value encountered in true_divide
> 
> When I try run vcf2smc and estimate without masking, it works fine. The mask seems fully valid, and vcf2smc conversion finishes normally with it. The number of observations written with mask also seems normal.
> Here are the examples of masked and unmasked smc files.
> https://www.dropbox.com/sh/yl7qxgz06ug2qay/AADPnd7SY875KG14SJHHUtMCa?dl=0
> 
> Commands I was using are:
> 
> smc++ vcf2smc --mask tst.mask.gz tst.vcf.gz tst_with_mask.smc.gz 21 TST:LP6005441-DNA_F08,LP6005442-DNA_D01,LP6005441-DNA_F04,LP6005441-DNA_E08,LP6005443-DNA_C02,LP6005441-DNA_D06,LP6005441-DNA_C06,LP6005443-DNA_C06,LP6005592-DNA_C02,LP6005519-DNA_B06
> 
> smc++ vcf2smc tst.vcf.gz tst_without_mask.smc.gz 21 TST:LP6005441-DNA_F08,LP6005442-DNA_D01,LP6005441-DNA_F04,LP6005441-DNA_E08,LP6005443-DNA_C02,LP6005441-DNA_D06,LP6005441-DNA_C06,LP6005443-DNA_C06,LP6005592-DNA_C02,LP6005519-DNA_B06
> 
> smc++ estimate -o tmp/ --cores 32 1.45e-8 tst_with_mask.smc.gz
> 
> smc++ estimate -o tmp/ --cores 32 1.45e-8 tst_without_mask.smc.gz
> 
> Thank you in advance!

Can you tell me how you generated the mask file for smc++? I'm struggling pretty heavily with that. Thank you!
