### ISSUE TITLE
Confidence intervals, ancestral state and split

### ISSUE THREAD

**Issue by mariels** [popgenmethods/smcpp#83]
Hello,

I have been using SMC++ to reconstruct the past demographic history of 6 populations each including 7-11 genomes with coverage around 6 to 11x (unphased). I have a few questions on the results and program.

I would be interested in estimating confidence intervals both for Ne and split times. I have read in the past messages that this can be done by bootstrapping and a user @biozzq is providing a script on thread #37. 
However, I'm not very familiar with python and I am not sure to understand which would be the different steps and which file should be the input file for the python script (the smc.gz files?). Would anyone be able to help? Many thanks.

I have been running the program considering that the ancestral state is not known. Is there an easy way to include the ancestral state?

I also would like to check if my interpretation of the split plots is correct. In the first plot below, the populations are estimated to split around 2*10^4 years ago and on the right around 10^5 before present. For the first plot, the split time is 0.13 in the  model.final.json file and for the second plot, the estimated split time is 0.86. How could I convert it to years?

![image](https://user-images.githubusercontent.com/20403796/40125363-a83825e4-5922-11e8-8747-a30b50e30c6a.png)

I have varied the distinguished individuals for the estimate command but not for the split command. Would you recommend varying them for the split command too?

Thank you very much for your time,
Best wishes,

Marie

**Comment by liveliiy** [comment]
Have you resolve the problem? I have same problem. There is one more question. How can you involve multiple contig to plot the last result?

**Comment by mariels** [comment]
Sorry I'm just going back to those analyses. No I haven't found a solution and would still be interested in getting help.

**Comment by mariels** [comment]
Dear @biozzq,

I am trying to run your script bootstrap_smcpp.py to generate input files for bootstrap estimates of population histories and split times.
Unfortunately I can't get it to work using the initial vcf file (including all chromosomes/scaffolds) or one smc.txt for one scaffold as an input file. 
Could you please let me know which input file should be used? 

@mmaalvarez I read you have used the script in another thread. Could you also maybe help?

Thank you very much,
Best wishes,

Marie
