### ISSUE TITLE
Creating bed mask files

### ISSUE THREAD

**Issue by mmaalvarez** [popgenmethods/smcpp#85]
Hi there, 

I wonder if you could point me out to any tool that can create .bed formatted mask files from multisample .vcf files. I started from individual .bam files, from which I created individual .vcf files using samtools (mpileup -q 20 -Q 20 -C 50 -u), and then merged these files into multisample .vcf files in order to use them as input for smc++. I created .bed formatted mask files for each individual using a msmc tool, bamCaller.py, but I do not know if it makes sense to merge these individual .bed mask files somehow and use them as a global mask file for the merged .vcf. Any ideas? 

Best,

Miguel

**Comment by dzaccook** [comment]
Hi, how did you deal with that?

**Comment by mmaalvarez** [comment]
Hi, I wrote a script for creating the masked .bed files from the multisample .vcf, I don't have access to it right now but will be in some days, if interested. Not sure if the assumptions I took were correct, but the final results seem to be fine.

**Comment by mayufeifei28** [comment]
Hi, I am having same issue with creating .bed formatted mask files from multisample .vcf files. By any chance, you have access to the script. Would you mind if you could share it. Thanks a lot!
