### ISSUE TITLE
can't use the lastest version

### ISSUE THREAD

**Issue by guzhongru** [popgenmethods/smcpp#9]
hi
I just can't install your lastest version by using anaconda3. So annoying. Can you please show me how to install it. Thanks in advance.

[surban@Admin ~/anaconda3/bin]$./conda install  -c terhorst -c bioconda -c conda-forge smcpp
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - smcpp -> ad >=1.3.2 -> python 3.5* -> sqlite 3.9.*
  - smcpp -> ad >=1.3.2 -> python 3.5* -> xz 5.0.*
Use "conda info <package>" to see the dependencies for each package.

**Comment by asifzubair** [comment]
@terhorst , please change the README to reflect that python version 3.5 or greater is required. Thank you.
