### ISSUE TITLE
h5py FutureWarning for smcpp  v1.15.0

### ISSUE THREAD

**Issue by jiyongkun** [popgenmethods/smcpp#95]
/home/share/biosoft/conda_env/smcpp/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

**Comment by terhorst** [comment]
Thanks for reporting. This is an upstream issue (h5py/h5py#974). It should not affect anything.
