### ISSUE TITLE
different results using different version

### ISSUE THREAD

**Issue by dzaccook** [popgenmethods/smcpp#96]
Hi,
I am getting different results of split using different version (1.11-dev vs 1.15). I had 120 samples come from two population (60 WEU samples, 60 CEU samples) and called SNP using GATK.
I run the program like this, 
smc++ vcf2smc my.vcf.gz data/pop1.smc.gz <contig> pop1:ind1_1,ind1_2.........
smc++ vcf2smc my.vcf.gz data/pop2.smc.gz <contig> pop2:ind2_1,ind2_2........
smc++ estimate -o pop1/ <mu> data/pop1.smc.gz 
smc++ estimate -o pop2/ <mu> data/pop2.smc.gz
smc++ vcf2smc my.vcf.gz data/pop12.smc.gz <contig> pop1:ind1_1,ind1_2 pop2:ind2_1,ind2_2......
smc++ vcf2smc my.vcf.gz data/pop21.smc.gz <contig> pop2:ind2_1,ind2_2 pop1:ind1_1,ind1_2......
smc++ split -o split/ pop1/model.final.json pop2/model.final.json data/*.smc.gz
smc++ plot joint.pdf split/model.final.json
The result of 1.11-dev:
[WEU_CEU.no_mask.joint.old.pdf](https://github.com/popgenmethods/smcpp/files/2350986/WEU_CEU.no_mask.joint.old.pdf)
The result of 1.15:
[WEU_CEU.no_mask.joint.pdf](https://github.com/popgenmethods/smcpp/files/2350987/WEU_CEU.no_mask.joint.pdf)
Can you give me some help?
Thank you!

**Comment by terhorst** [comment]
Thanks for reporting. Others have reported this as well. I may have introduced a bug somewhere. I am investigating.
