### ISSUE TITLE
a problem in estimate

### ISSUE THREAD

**Issue by liveliiy** [popgenmethods/smcpp#97]
Hi
I have a problem when I use estimate. Here is my code
smc++ estimate --cores 2 -o testm/ 6.18e-8 data/pop1_scaffold-*.smc.gz
here is the error
1250 smcpp.analysis.base INFO theta: 0.000100
1251 smcpp.analysis.base INFO rho: 0.000100
1252 smcpp.data_filter INFO Loading data...
and then it stopped with no error. I first thought it need a long time to load data but it seems too long so I guess there is some problem.
Can you give me some help?
Thank you!

**Comment by benmoran11** [comment]
Hi liveliiy,
Did you find the cause of the problem? My SMC++ is also freezing with a "loading data" message, sometimes before the EM steps, sometimes after. I am using the cv function, not estimate, but I thought the answer might be the same.
Thanks!

**Comment by liveliiy** [comment]
Hi Ben
I found my problem is not installed the program successfully. Now I use version 1.11 instead of 1.15 cause there is an issue caused by different version and the author reply there is a bug in 1.15. I don't know have they solved that problem yet.

**Comment by benmoran11** [comment]
Ok, I'll try returning to a previous version. Thank you!
